-- Generated by Mocodo 4.3.3

CREATE TABLE ACTIVITY_BUCKET_CACHE_V2_pri_ (
  PRIMARY KEY (target_user_id),
  target_user_id VARCHAR(42) NOT NULL,
  range_days     VARCHAR(42),
  view_kind      VARCHAR(42),
  exclude_key    VARCHAR(42),
  summary_json   VARCHAR(42),
  built_at       VARCHAR(42)
);

CREATE TABLE ACTIVITY_SESSION_pri_ (
  PRIMARY KEY (session_id),
  session_id      VARCHAR(42) NOT NULL,
  start_at        VARCHAR(42),
  end_at          VARCHAR(42),
  is_open_tail    VARCHAR(42),
  source_revision VARCHAR(42),
  user_id         VARCHAR(42) NOT NULL
);

CREATE TABLE ACTIVITY_SYNC_STATE_V2_pri_ (
  PRIMARY KEY (updated_at),
  updated_at               VARCHAR(42) NOT NULL,
  is_self                  VARCHAR(42),
  source_last_created_at   VARCHAR(42),
  pending_session_start_at VARCHAR(42),
  cached_range_days        VARCHAR(42),
  user_id                  VARCHAR(42) NOT NULL
);

CREATE TABLE AVATAR_MEMO_pub_ (
  PRIMARY KEY (edited_at),
  edited_at VARCHAR(42) NOT NULL,
  memo      VARCHAR(42),
  avatar_id VARCHAR(42) NOT NULL
);

CREATE TABLE AVATAR_TAG_pub_ (
  PRIMARY KEY (tag),
  tag   VARCHAR(42) NOT NULL,
  color VARCHAR(42)
);

CREATE TABLE AVATAR_pub_ (
  PRIMARY KEY (avatar_id),
  avatar_id           VARCHAR(42) NOT NULL,
  name                VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE BUCKET_FOR (
  PRIMARY KEY (target_user_id, user_id),
  target_user_id VARCHAR(42) NOT NULL,
  user_id        VARCHAR(42) NOT NULL
);

CREATE TABLE CACHE_AVATAR_pub_ (
  PRIMARY KEY (id),
  id                  VARCHAR(42) NOT NULL,
  added_at            VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  created_at          VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  name                VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  updated_at          VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE CACHE_WORLD_pub_ (
  PRIMARY KEY (id),
  id                  VARCHAR(42) NOT NULL,
  added_at            VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  created_at          VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  name                VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  updated_at          VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE CONFIG_pub_ (
  PRIMARY KEY (key),
  key   VARCHAR(42) NOT NULL,
  value VARCHAR(42)
);

CREATE TABLE COOKIE_pub_ (
  PRIMARY KEY (key),
  key   VARCHAR(42) NOT NULL,
  value VARCHAR(42)
);

CREATE TABLE FAVORITE_AVATAR_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42),
  avatar_id  VARCHAR(42) NOT NULL
);

CREATE TABLE FAVORITE_FRIEND_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42)
);

CREATE TABLE FAVORITE_WORLD_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42),
  world_id   VARCHAR(42) NOT NULL
);

CREATE TABLE FAV_FRIEND_OF (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE FEED_AVATAR_pri_ (
  PRIMARY KEY (id),
  id                                 VARCHAR(42) NOT NULL,
  created_at                         VARCHAR(42),
  owner_id                           VARCHAR(42),
  avatar_name                        VARCHAR(42),
  current_avatar_image_url           VARCHAR(42),
  current_avatar_thumbnail_image_url VARCHAR(42)
);

CREATE TABLE FEED_BIO_pri_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  bio          VARCHAR(42),
  previous_bio VARCHAR(42)
);

CREATE TABLE FEED_GPS_pri_ (
  PRIMARY KEY (id),
  id                VARCHAR(42) NOT NULL,
  created_at        VARCHAR(42),
  location          VARCHAR(42),
  world_name        VARCHAR(42),
  previous_location VARCHAR(42),
  time              VARCHAR(42),
  group_name        VARCHAR(42)
);

CREATE TABLE FEED_ONLINE_OFFLINE_pri_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  type       VARCHAR(42),
  location   VARCHAR(42),
  world_name VARCHAR(42),
  time       VARCHAR(42),
  group_name VARCHAR(42)
);

CREATE TABLE FEED_STATUS_pri_ (
  PRIMARY KEY (id),
  id                          VARCHAR(42) NOT NULL,
  created_at                  VARCHAR(42),
  status                      VARCHAR(42),
  status_description          VARCHAR(42),
  previous_status             VARCHAR(42),
  previous_status_description VARCHAR(42)
);

CREATE TABLE FRIEND_LOG_CURRENT_pri_ (
  PRIMARY KEY (display_name),
  display_name  VARCHAR(42) NOT NULL,
  trust_level   VARCHAR(42),
  friend_number VARCHAR(42),
  user_id       VARCHAR(42) NOT NULL
);

CREATE TABLE FRIEND_LOG_HISTORY_pri_ (
  PRIMARY KEY (id),
  id                    VARCHAR(42) NOT NULL,
  created_at            VARCHAR(42),
  type                  VARCHAR(42),
  display_name          VARCHAR(42),
  previous_display_name VARCHAR(42),
  trust_level           VARCHAR(42),
  previous_trust_level  VARCHAR(42),
  friend_number         VARCHAR(42)
);

CREATE TABLE GAMELOG_EVENT_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  data       VARCHAR(42)
);

CREATE TABLE GAMELOG_EXTERNAL_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  message      VARCHAR(42),
  display_name VARCHAR(42),
  user_id      VARCHAR(42),
  location     VARCHAR(42)
);

CREATE TABLE GAMELOG_JOIN_LEAVE_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  type         VARCHAR(42),
  display_name VARCHAR(42),
  location     VARCHAR(42),
  time         VARCHAR(42)
);

CREATE TABLE GAMELOG_LOCATION_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  location   VARCHAR(42),
  time       VARCHAR(42),
  group_name VARCHAR(42),
  world_id   VARCHAR(42) NOT NULL
);

CREATE TABLE GAMELOG_PORTAL_SPAWN_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  display_name VARCHAR(42),
  location     VARCHAR(42),
  user_id      VARCHAR(42),
  instance_id  VARCHAR(42),
  world_name   VARCHAR(42)
);

CREATE TABLE GAMELOG_RESOURCE_LOAD_pub_ (
  PRIMARY KEY (id),
  id            VARCHAR(42) NOT NULL,
  created_at    VARCHAR(42),
  resource_url  VARCHAR(42),
  resource_type VARCHAR(42),
  location      VARCHAR(42)
);

CREATE TABLE GAMELOG_VIDEO_PLAY_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  video_url    VARCHAR(42),
  video_name   VARCHAR(42),
  video_id     VARCHAR(42),
  location     VARCHAR(42),
  display_name VARCHAR(42),
  user_id      VARCHAR(42)
);

CREATE TABLE HAS_AVATAR (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE HAS_BIO (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE HAS_STATUS (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE IS_ONLINE (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE JOIN_BY (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE LOGGED (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE MANUAL_RELATION_pri_ (
  PRIMARY KEY (user_id_a),
  user_id_a     VARCHAR(42) NOT NULL,
  user_id_b     VARCHAR(42),
  relation_type VARCHAR(42),
  added_at      VARCHAR(42)
);

CREATE TABLE MEMO_pub_ (
  PRIMARY KEY (edited_at),
  edited_at VARCHAR(42) NOT NULL,
  memo      VARCHAR(42),
  user_id   VARCHAR(42) NOT NULL
);

CREATE TABLE MODERATION_pri_ (
  PRIMARY KEY (updated_at),
  updated_at   VARCHAR(42) NOT NULL,
  display_name VARCHAR(42),
  block        VARCHAR(42),
  mute         VARCHAR(42),
  user_id      VARCHAR(42) NOT NULL
);

CREATE TABLE MUTUAL_GRAPH_FRIEND_OLD_pri_ (
  PRIMARY KEY (friend_id),
  friend_id    VARCHAR(42) NOT NULL,
  last_updated VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_LINK (
  PRIMARY KEY (friend_id_1, friend_id_2),
  friend_id_1 VARCHAR(42) NOT NULL,
  friend_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE MUTUAL_GRAPH_LINK_OLD (
  PRIMARY KEY (friend_id_1, friend_id_2),
  friend_id_1 VARCHAR(42) NOT NULL,
  friend_id_2 VARCHAR(42) NOT NULL,
  date        VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_META_pri_ (
  PRIMARY KEY (friend_id),
  friend_id       VARCHAR(42) NOT NULL,
  last_fetched_at VARCHAR(42),
  opted_out       VARCHAR(42),
  friend_id_2     VARCHAR(42) NOT NULL
);

CREATE TABLE NOTES_pri_ (
  PRIMARY KEY (note),
  note       VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  user_id    VARCHAR(42) NOT NULL
);

CREATE TABLE NOTIFICATION_V2_pri_ (
  PRIMARY KEY (id),
  id              VARCHAR(42) NOT NULL,
  created_at      VARCHAR(42),
  updated_at      VARCHAR(42),
  expires_at      VARCHAR(42),
  type            VARCHAR(42),
  link            VARCHAR(42),
  link_text       VARCHAR(42),
  message         VARCHAR(42),
  title           VARCHAR(42),
  image_url       VARCHAR(42),
  seen            VARCHAR(42),
  sender_user_id  VARCHAR(42),
  sender_username VARCHAR(42),
  data            VARCHAR(42),
  responses       VARCHAR(42),
  details         VARCHAR(42)
);

CREATE TABLE NOTIFICATION_pri_ (
  PRIMARY KEY (id),
  id               VARCHAR(42) NOT NULL,
  created_at       VARCHAR(42),
  type             VARCHAR(42),
  message          VARCHAR(42),
  world_name       VARCHAR(42),
  image_url        VARCHAR(42),
  invite_message   VARCHAR(42),
  request_message  VARCHAR(42),
  response_message VARCHAR(42),
  expired          VARCHAR(42),
  user_id_1        VARCHAR(42) NOT NULL,
  sender_username  VARCHAR(42),
  user_id_2        VARCHAR(42) NOT NULL,
  receiver_user_id VARCHAR(42)
);

CREATE TABLE NOTIF_V2_FOR (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE POSTED (
  PRIMARY KEY (user_id, id),
  user_id VARCHAR(42) NOT NULL,
  id      VARCHAR(42) NOT NULL
);

CREATE TABLE RELATED (
  PRIMARY KEY (user_id_1, user_id_2),
  user_id_1     VARCHAR(42) NOT NULL,
  user_id_2     VARCHAR(42) NOT NULL,
  relation_type VARCHAR(42)
);

CREATE TABLE TAGGED (
  PRIMARY KEY (avatar_id, tag),
  avatar_id VARCHAR(42) NOT NULL,
  tag       VARCHAR(42) NOT NULL
);

CREATE TABLE TRACKED_BY (
  PRIMARY KEY (user_id_1, user_id_2),
  user_id_1 VARCHAR(42) NOT NULL,
  user_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE TRACKED_NONFRIEND_pri_ (
  PRIMARY KEY (user_id),
  user_id      VARCHAR(42) NOT NULL,
  display_name VARCHAR(42),
  added_at     VARCHAR(42)
);

CREATE TABLE USER_pri_ (
  PRIMARY KEY (user_id),
  user_id       VARCHAR(42) NOT NULL,
  display_name  VARCHAR(42),
  trust_level   VARCHAR(42),
  friend_number VARCHAR(42)
);

CREATE TABLE WORLD_MEMO_pub_ (
  PRIMARY KEY (edited_at),
  edited_at VARCHAR(42) NOT NULL,
  memo      VARCHAR(42),
  world_id  VARCHAR(42) NOT NULL
);

CREATE TABLE WORLD_pub_ (
  PRIMARY KEY (world_id),
  world_id            VARCHAR(42) NOT NULL,
  name                VARCHAR(42),
  description         VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  image_url           VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  version             VARCHAR(42)
);

ALTER TABLE ACTIVITY_SESSION_pri_ ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE ACTIVITY_SYNC_STATE_V2_pri_ ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE AVATAR_MEMO_pub_ ADD FOREIGN KEY (avatar_id) REFERENCES AVATAR (pub) (avatar_id);

ALTER TABLE BUCKET_FOR ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);
ALTER TABLE BUCKET_FOR ADD FOREIGN KEY (target_user_id) REFERENCES ACTIVITY_BUCKET_CACHE_V2 (pri) (target_user_id);

ALTER TABLE FAVORITE_AVATAR_pub_ ADD FOREIGN KEY (avatar_id) REFERENCES AVATAR (pub) (avatar_id);

ALTER TABLE FAVORITE_WORLD_pub_ ADD FOREIGN KEY (world_id) REFERENCES WORLD (pub) (world_id);

ALTER TABLE FAV_FRIEND_OF ADD FOREIGN KEY (id) REFERENCES FAVORITE_FRIEND (pub) (id);
ALTER TABLE FAV_FRIEND_OF ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE FRIEND_LOG_CURRENT_pri_ ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE GAMELOG_LOCATION_pub_ ADD FOREIGN KEY (world_id) REFERENCES WORLD (pub) (world_id);

ALTER TABLE HAS_AVATAR ADD FOREIGN KEY (id) REFERENCES FEED_AVATAR (pri) (id);
ALTER TABLE HAS_AVATAR ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE HAS_BIO ADD FOREIGN KEY (id) REFERENCES FEED_BIO (pri) (id);
ALTER TABLE HAS_BIO ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE HAS_STATUS ADD FOREIGN KEY (id) REFERENCES FEED_STATUS (pri) (id);
ALTER TABLE HAS_STATUS ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE IS_ONLINE ADD FOREIGN KEY (id) REFERENCES FEED_ONLINE_OFFLINE (pri) (id);
ALTER TABLE IS_ONLINE ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE JOIN_BY ADD FOREIGN KEY (id) REFERENCES GAMELOG_JOIN_LEAVE (pub) (id);
ALTER TABLE JOIN_BY ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE LOGGED ADD FOREIGN KEY (id) REFERENCES FRIEND_LOG_HISTORY (pri) (id);
ALTER TABLE LOGGED ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE MEMO_pub_ ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE MODERATION_pri_ ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE MUTUAL_GRAPH_LINK_OLD ADD FOREIGN KEY (friend_id_2) REFERENCES MUTUAL_GRAPH_FRIEND_OLD (pri) (friend_id);
ALTER TABLE MUTUAL_GRAPH_LINK_OLD ADD FOREIGN KEY (friend_id_1) REFERENCES MUTUAL_GRAPH_FRIEND_OLD (pri) (friend_id);

ALTER TABLE NOTES_pri_ ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE NOTIFICATION_pri_ ADD FOREIGN KEY (user_id_2) REFERENCES USER (pri) (user_id);
ALTER TABLE NOTIFICATION_pri_ ADD FOREIGN KEY (user_id_1) REFERENCES USER (pri) (user_id);

ALTER TABLE NOTIF_V2_FOR ADD FOREIGN KEY (id) REFERENCES NOTIFICATION_V2 (pri) (id);
ALTER TABLE NOTIF_V2_FOR ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE POSTED ADD FOREIGN KEY (id) REFERENCES FEED_GPS (pri) (id);
ALTER TABLE POSTED ADD FOREIGN KEY (user_id) REFERENCES USER (pri) (user_id);

ALTER TABLE RELATED ADD FOREIGN KEY (user_id_2) REFERENCES USER (pri) (user_id);
ALTER TABLE RELATED ADD FOREIGN KEY (user_id_1) REFERENCES USER (pri) (user_id);

ALTER TABLE TAGGED ADD FOREIGN KEY (tag) REFERENCES AVATAR_TAG (pub) (tag);
ALTER TABLE TAGGED ADD FOREIGN KEY (avatar_id) REFERENCES AVATAR (pub) (avatar_id);

ALTER TABLE TRACKED_BY ADD FOREIGN KEY (user_id_2) REFERENCES TRACKED_NONFRIEND (pri) (user_id);
ALTER TABLE TRACKED_BY ADD FOREIGN KEY (user_id_1) REFERENCES USER (pri) (user_id);

ALTER TABLE WORLD_MEMO_pub_ ADD FOREIGN KEY (world_id) REFERENCES WORLD (pub) (world_id);
