-- Generated by Mocodo 4.3.3

CREATE TABLE ACTIVITY_BUCKET_CACHE_V2_pri_ (
  PRIMARY KEY (user_id),
  user_id        VARCHAR(42) NOT NULL,
  target_user_id VARCHAR(42),
  range_days     VARCHAR(42),
  view_kind      VARCHAR(42),
  exclude_key    VARCHAR(42),
  summary_json   VARCHAR(42),
  built_at       VARCHAR(42)
);

CREATE TABLE ACTIVITY_SESSION_V2_pri_ (
  PRIMARY KEY (session_id),
  session_id      VARCHAR(42) NOT NULL,
  start_at        VARCHAR(42),
  end_at          VARCHAR(42),
  is_open_tail    VARCHAR(42),
  source_revision VARCHAR(42),
  user_id         VARCHAR(42)
);

CREATE TABLE ACTIVITY_SYNC_STATE_V2_pri_ (
  PRIMARY KEY (user_id),
  user_id                  VARCHAR(42) NOT NULL,
  updated_at               VARCHAR(42),
  is_self                  VARCHAR(42),
  source_last_created_at   VARCHAR(42),
  pending_session_start_at VARCHAR(42),
  cached_range_days        VARCHAR(42)
);

CREATE TABLE AVATAR_HISTORY_pri_ (
  PRIMARY KEY (avatar_id),
  avatar_id  VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  time       VARCHAR(42)
);

CREATE TABLE AVATAR_MEMO_pub_ (
  PRIMARY KEY (avatar_id),
  avatar_id VARCHAR(42) NOT NULL,
  edited_at VARCHAR(42),
  memo      VARCHAR(42)
);

CREATE TABLE AVATAR_TAG_pub_ (
  PRIMARY KEY (avatar_id),
  avatar_id VARCHAR(42) NOT NULL,
  tag       VARCHAR(42),
  color     VARCHAR(42)
);

CREATE TABLE AVATAR_pub_ (
  PRIMARY KEY (avatar_id),
  avatar_id           VARCHAR(42) NOT NULL,
  name                VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE CACHE_AVATAR_pub_ (
  PRIMARY KEY (id),
  id                  VARCHAR(42) NOT NULL,
  added_at            VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  created_at          VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  name                VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  updated_at          VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE CACHE_WORLD_pub_ (
  PRIMARY KEY (id),
  id                  VARCHAR(42) NOT NULL,
  added_at            VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  created_at          VARCHAR(42),
  description         VARCHAR(42),
  image_url           VARCHAR(42),
  name                VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  updated_at          VARCHAR(42),
  version             VARCHAR(42)
);

CREATE TABLE CONFIGS_pub_ (
  PRIMARY KEY (key),
  key   VARCHAR(42) NOT NULL,
  value VARCHAR(42)
);

CREATE TABLE COOKIES_pub_ (
  PRIMARY KEY (key),
  key   VARCHAR(42) NOT NULL,
  value VARCHAR(42)
);

CREATE TABLE FAVORITE_AVATAR_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42),
  avatar_id  VARCHAR(42)
);

CREATE TABLE FAVORITE_FRIEND_pub_ (
  PRIMARY KEY (id),
  id          VARCHAR(42) NOT NULL,
  created_at  VARCHAR(42),
  group_name  VARCHAR(42),
  user_id_ref VARCHAR(42)
);

CREATE TABLE FAVORITE_WORLD_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  group_name VARCHAR(42),
  world_id   VARCHAR(42)
);

CREATE TABLE FEED_AVATAR_pri_ (
  PRIMARY KEY (id),
  id                                 VARCHAR(42) NOT NULL,
  created_at                         VARCHAR(42),
  owner_id                           VARCHAR(42),
  avatar_name                        VARCHAR(42),
  current_avatar_image_url           VARCHAR(42),
  current_avatar_thumbnail_image_url VARCHAR(42),
  user_id                            VARCHAR(42)
);

CREATE TABLE FEED_BIO_pri_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  bio          VARCHAR(42),
  previous_bio VARCHAR(42),
  user_id      VARCHAR(42)
);

CREATE TABLE FEED_GPS_pri_ (
  PRIMARY KEY (id),
  id                VARCHAR(42) NOT NULL,
  created_at        VARCHAR(42),
  location          VARCHAR(42),
  world_name        VARCHAR(42),
  previous_location VARCHAR(42),
  time              VARCHAR(42),
  group_name        VARCHAR(42),
  user_id           VARCHAR(42)
);

CREATE TABLE FEED_ONLINE_OFFLINE_pri_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  type       VARCHAR(42),
  location   VARCHAR(42),
  world_name VARCHAR(42),
  time       VARCHAR(42),
  group_name VARCHAR(42),
  user_id    VARCHAR(42)
);

CREATE TABLE FEED_STATUS_pri_ (
  PRIMARY KEY (id),
  id                          VARCHAR(42) NOT NULL,
  created_at                  VARCHAR(42),
  status                      VARCHAR(42),
  status_description          VARCHAR(42),
  previous_status             VARCHAR(42),
  previous_status_description VARCHAR(42),
  user_id                     VARCHAR(42)
);

CREATE TABLE FRIEND_LOG_CURRENT_pri_ (
  PRIMARY KEY (user_id),
  user_id       VARCHAR(42) NOT NULL,
  display_name  VARCHAR(42),
  trust_level   VARCHAR(42),
  friend_number VARCHAR(42)
);

CREATE TABLE FRIEND_LOG_HISTORY_pri_ (
  PRIMARY KEY (id),
  id                    VARCHAR(42) NOT NULL,
  created_at            VARCHAR(42),
  type                  VARCHAR(42),
  display_name          VARCHAR(42),
  previous_display_name VARCHAR(42),
  trust_level           VARCHAR(42),
  previous_trust_level  VARCHAR(42),
  friend_number         VARCHAR(42),
  user_id               VARCHAR(42)
);

CREATE TABLE GAMELOG_EVENT_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  data       VARCHAR(42)
);

CREATE TABLE GAMELOG_EXTERNAL_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  message      VARCHAR(42),
  display_name VARCHAR(42),
  user_id      VARCHAR(42),
  location     VARCHAR(42)
);

CREATE TABLE GAMELOG_JOIN_LEAVE_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  type         VARCHAR(42),
  display_name VARCHAR(42),
  user_id      VARCHAR(42),
  time         VARCHAR(42),
  location     VARCHAR(42)
);

CREATE TABLE GAMELOG_LOCATION_pub_ (
  PRIMARY KEY (id),
  id         VARCHAR(42) NOT NULL,
  created_at VARCHAR(42),
  location   VARCHAR(42),
  time       VARCHAR(42),
  group_name VARCHAR(42),
  world_id   VARCHAR(42)
);

CREATE TABLE GAMELOG_PORTAL_SPAWN_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  display_name VARCHAR(42),
  location     VARCHAR(42),
  user_id      VARCHAR(42),
  instance_id  VARCHAR(42),
  world_name   VARCHAR(42)
);

CREATE TABLE GAMELOG_RESOURCE_LOAD_pub_ (
  PRIMARY KEY (id),
  id            VARCHAR(42) NOT NULL,
  created_at    VARCHAR(42),
  resource_url  VARCHAR(42),
  resource_type VARCHAR(42),
  location      VARCHAR(42)
);

CREATE TABLE GAMELOG_VIDEO_PLAY_pub_ (
  PRIMARY KEY (id),
  id           VARCHAR(42) NOT NULL,
  created_at   VARCHAR(42),
  video_url    VARCHAR(42),
  video_name   VARCHAR(42),
  video_id     VARCHAR(42),
  location     VARCHAR(42),
  display_name VARCHAR(42),
  user_id      VARCHAR(42)
);

CREATE TABLE MANUAL_RELATIONS_MANUEL_pri_ (
  PRIMARY KEY (user_id_a),
  user_id_a     VARCHAR(42) NOT NULL,
  user_id_b     VARCHAR(42),
  relation_type VARCHAR(42),
  added_at      VARCHAR(42)
);

CREATE TABLE MEMO_pub_ (
  PRIMARY KEY (user_id_ref2),
  user_id_ref2 VARCHAR(42) NOT NULL,
  edited_at    VARCHAR(42),
  memo         VARCHAR(42)
);

CREATE TABLE MODERATION_pri_ (
  PRIMARY KEY (user_id),
  user_id      VARCHAR(42) NOT NULL,
  updated_at   VARCHAR(42),
  display_name VARCHAR(42),
  block        VARCHAR(42),
  mute         VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_FRIENDS_OLD_pri_ (
  PRIMARY KEY (friend_id),
  friend_id    VARCHAR(42) NOT NULL,
  last_updated VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_LINKS_OLD_pri_ (
  PRIMARY KEY (friend_id),
  friend_id VARCHAR(42) NOT NULL,
  mutual_id VARCHAR(42),
  date      VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_LINKS_pri_ (
  PRIMARY KEY (friend_id),
  friend_id VARCHAR(42) NOT NULL,
  mutual_id VARCHAR(42)
);

CREATE TABLE MUTUAL_GRAPH_META_pri_ (
  PRIMARY KEY (friend_id),
  friend_id       VARCHAR(42) NOT NULL,
  last_fetched_at VARCHAR(42),
  opted_out       VARCHAR(42)
);

CREATE TABLE NOTES_pri_ (
  PRIMARY KEY (user_id),
  user_id      VARCHAR(42) NOT NULL,
  display_name VARCHAR(42),
  note         VARCHAR(42),
  created_at   VARCHAR(42)
);

CREATE TABLE NOTIFICATIONS_V2_pri_ (
  PRIMARY KEY (user_id),
  user_id         VARCHAR(42) NOT NULL,
  id              VARCHAR(42),
  created_at      VARCHAR(42),
  updated_at      VARCHAR(42),
  expires_at      VARCHAR(42),
  type            VARCHAR(42),
  link            VARCHAR(42),
  link_text       VARCHAR(42),
  message         VARCHAR(42),
  title           VARCHAR(42),
  image_url       VARCHAR(42),
  seen            VARCHAR(42),
  sender_user_id  VARCHAR(42),
  sender_username VARCHAR(42),
  data            VARCHAR(42),
  responses       VARCHAR(42),
  details         VARCHAR(42)
);

CREATE TABLE NOTIFICATION_pri_ (
  PRIMARY KEY (id),
  id               VARCHAR(42) NOT NULL,
  created_at       VARCHAR(42),
  type             VARCHAR(42),
  message          VARCHAR(42),
  world_name       VARCHAR(42),
  image_url        VARCHAR(42),
  invite_message   VARCHAR(42),
  request_message  VARCHAR(42),
  response_message VARCHAR(42),
  expired          VARCHAR(42),
  sender_user_id   VARCHAR(42),
  receiver_user_id VARCHAR(42)
);

CREATE TABLE TRACKED_NONFRIENDS_pri_ (
  PRIMARY KEY (user_id),
  user_id      VARCHAR(42) NOT NULL,
  display_name VARCHAR(42),
  added_at     VARCHAR(42)
);

CREATE TABLE USER_pri_ (
  PRIMARY KEY (user_id),
  user_id       VARCHAR(42) NOT NULL,
  display_name  VARCHAR(42),
  trust_level   VARCHAR(42),
  friend_number VARCHAR(42)
);

CREATE TABLE WORLD_MEMO_pub_ (
  PRIMARY KEY (world_id),
  world_id  VARCHAR(42) NOT NULL,
  edited_at VARCHAR(42),
  memo      VARCHAR(42)
);

CREATE TABLE WORLD_pub_ (
  PRIMARY KEY (world_id),
  world_id            VARCHAR(42) NOT NULL,
  name                VARCHAR(42),
  description         VARCHAR(42),
  author_id           VARCHAR(42),
  author_name         VARCHAR(42),
  image_url           VARCHAR(42),
  release_status      VARCHAR(42),
  thumbnail_image_url VARCHAR(42),
  version             VARCHAR(42)
);
