// Phase 9 slice S9 (task 9.13) — SQLite → remote-engine cross-engine migration.
//
// Provides `migrateSqliteToRemote(srcConnStr, options)` which copies
// every global + user table from a source SQLite database into the currently
// initialised remote target (PostgreSQL or MySQL/MariaDB). The destination is
// the singleton `adapter` from `./adapter/index.js` — a `PgSQLAdapter` when
// `VRCX_Database.mode === 'postgresql'` or a `MySQLAdapter` when mode is
// `'mysql'`/`'mariadb'`, each saved + the app restarted so the C#
// `PostgreSQL.Instance` / `MySQL.Instance` pool is initialised before the
// renderer boots. `migrateSqliteToPgsql` is kept as a backward-compatible alias.
//
// The migration body is engine-agnostic: it only touches the abstract
// `EngineAdapter` surface (`initGlobalSchema` / `initUserSchema` / `userTable`
// / `bulkInsert`), which every remote subclass implements, so the same code
// path serves both PG and MySQL destinations.
//
// NOTE: the destination is the live singleton only — there is no `dstConfig`
// parameter. Callers MUST ensure the engine has been switched + the app
// restarted so the singleton matches the user's intended target; the UI-side
// guard `canMigrateToRemote` in `stores/settings/advanced.js` enforces this by
// comparing the current UI refs against the boot-time config snapshot
// (`bootDbConfig` from `plugins/interopApi.js`). Passing a candidate target
// config here would be misleading: it could never override the already-Init'd
// C# pool, so any mismatch between the form and the running pool would silently
// route the migration to the wrong host. See defect 3 (MEDIUM) fix.
//
// See `docs/PHASE9_PGSQL_DESIGN.md` §6.2 + §11.1 9.13 DoD.
//
// Design constraints honoured here:
//   - R6: `activity_sessions_v2` uses `GENERATED BY DEFAULT AS IDENTITY`, so
//     explicit `session_id` values copied from SQLite are accepted by PG.
//   - `id` / `session_id` columns are copied verbatim (SELECT * includes
//     them, bulkInsert writes them through).
//   - Errors per-table are collected and the run continues — a single broken
//     table does not abort the whole migration.
//   - Row-count verification per table; deeper sampling left to S12.

import { adapter, createAdapter } from './adapter/index.js';

/**
 * 16 global tables (public schema) — mirrors `SQLiteAdapter.initGlobalSchema`
 * (L985-1049), `PgSQLAdapter.initGlobalSchema` (L1293-1341) and
 * `MySQLAdapter.initGlobalSchema` table-for-table. Order matches the
 * schema-init order so the migration log reads naturally.
 * @type {string[]}
 */
const GLOBAL_TABLES = [
    'gamelog_location',
    'gamelog_join_leave',
    'gamelog_portal_spawn',
    'gamelog_video_play',
    'gamelog_resource_load',
    'gamelog_event',
    'gamelog_external',
    'cache_avatar',
    'cache_world',
    'favorite_world',
    'favorite_avatar',
    'favorite_friend',
    'memos',
    'world_memos',
    'avatar_memos',
    'avatar_tags'
];

/**
 * 22 user-table base names — mirrors `PgSQLAdapter.initUserSchema` (L1133-1206)
 * / `SQLiteAdapter.initUserSchema` (L900-979) / `MySQLAdapter.initUserSchema`.
 * In the source SQLite DB these live flat as `${prefix}_${name}`; in a
 * destination PG DB they live in the `account_${prefix}` schema as just
 * `${name}`, and in a destination MySQL DB they live as the prefixed name
 * `${prefix}_${name}` (see `userTable(prefix, name)` — each adapter resolves
 * the destination identifier itself, so this list is engine-agnostic).
 *
 * Sorted longest-first when matching so e.g. `activity_sync_state_v2` is tried
 * before `activity_sessions_v2` (no overlap here, but the rule is defensive
 * against future additions).
 * @type {string[]}
 */
const USER_TABLE_NAMES = [
    'activity_bucket_cache_v2',
    'activity_sync_state_v2',
    'activity_sessions_v2',
    'manual_relations_MANUEL',
    'mutual_graph_friends_old',
    'mutual_graph_links_old',
    'mutual_graph_friends',
    'mutual_graph_links',
    'mutual_graph_meta',
    'feed_online_offline',
    'friend_log_current',
    'friend_log_history',
    'tracked_nonfriends',
    'notifications_v2',
    'notifications',
    'avatar_history',
    'feed_status',
    'feed_avatar',
    'feed_gps',
    'feed_bio',
    'moderation',
    'notes'
];

// Longest-first for `endsWith('_' + name)` matching.
const USER_TABLE_NAMES_BY_LENGTH_DESC = [...USER_TABLE_NAMES].sort(
    (a, b) => b.length - a.length
);

/**
 * @typedef {Object} MigrationProgress
 * @property {'global'|'user'} phase
 * @property {string} table - destination table identifier (bare name or `account_{prefix}.{name}`)
 * @property {number} current - 1-based index of the current table within its phase
 * @property {number} total - total tables in this phase
 * @property {number} rowsCopied - running total rows copied across all tables so far
 */

/**
 * @typedef {Object} MigrationResult
 * @property {number} globalTables - number of global tables processed
 * @property {number} userTables - number of user tables processed (across all prefixes)
 * @property {number} rowsCopied - total rows copied
 * @property {string[]} errors - per-table error messages (empty on full success)
 */

/**
 * Migrate data from a SQLite database to a remote-engine target
 * (PostgreSQL or MySQL/MariaDB).
 *
 * The destination is the singleton `adapter` from `./adapter/index.js`, which
 * is a `PgSQLAdapter` when the app booted with `VRCX_Database.mode ===
 * 'postgresql'` (C# `PostgreSQL` pool initialised) or a `MySQLAdapter` when
 * mode is `'mysql'`/`'mariadb'` (C# `MySQL` initialised). Callers must ensure
 * the engine has been switched + the app restarted before invoking this
 * function; otherwise the destination writes will go to the live SQLite
 * adapter and corrupt it. We guard against this by refusing to run when the
 * singleton's `engineType` is `'sqlite'` (or the abstract `'unknown'`).
 *
 * The body is engine-agnostic: it only touches abstract `EngineAdapter`
 * methods every remote subclass implements, so PG and MySQL share one code
 * path. `isConnected` (a PgSQLAdapter extension) is probed best-effort when
 * present; subclasses without it are assumed connected after a successful Init.
 *
 * There is intentionally NO `dstConfig` parameter: the destination is always
 * the live singleton, whose connection was fixed at boot by the C# layer.
 * Accepting a candidate target config would let a caller pass values that
 * disagree with the running pool, creating the illusion that the migration
 * honours them while it actually writes to the boot-time connection (defect 3).
 * The caller-side guard `canMigrateToRemote` blocks that case before invoking
 * this function.
 *
 * @param {string} srcConnStr - SQLite connection string like 'sqlite:///C:/path/to/old.db'.
 * @param {object} [options] - Optional { batchSize=500, onProgress? }.
 * @param {number} [options.batchSize=500] - rows per bulkInsert call (PG param limit 65535; 500 rows × ~50 cols is safe; MySQL prepared-statement limit is similar).
 * @param {(p: MigrationProgress) => void} [options.onProgress] - progress callback for UI.
 * @returns {Promise<MigrationResult>}
 */
export async function migrateSqliteToRemote(
    srcConnStr,
    options = {}
) {
    const { batchSize = 500, onProgress } = options;
    const errors = [];
    let rowsCopied = 0;
    let globalTables = 0;
    let userTables = 0;

    // ── 0. Guards ────────────────────────────────────────────────────
    // The destination must NOT be a SQLiteAdapter. If it is, the user
    // hasn't switched engine + restarted yet — refuse to run rather than
    // silently corrupt the live SQLite database.
    //
    // Original M1 fix (QA M1 + Security M1) used `dropUserSchema` as a
    // PgSQLAdapter-only discriminator, but that made the migration
    // Pg-only and excluded MySQLAdapter (which deliberately has no
    // `dropUserSchema` because MySQL stores user tables flat under a
    // `prefix_` naming scheme rather than in per-account schemas). To treat
    // both remote engines uniformly we now gate on `adapter.engineType` —
    // an abstract getter every subclass overrides — and accept any value
    // that isn't `'sqlite'` (or the abstract default `'unknown'`).
    const engine =
        /** @type {{ engineType?: string, isConnected?: () => boolean }} */ (
            adapter
        ).engineType;
    if (!engine || engine === 'sqlite' || engine === 'unknown') {
        throw new Error(
            'migrateSqliteToRemote: destination adapter is the default SQLite engine. ' +
                'Switch VRCX_Database.mode to "postgresql", "mysql" or "mariadb" and ' +
                'restart the app before running the migration.'
        );
    }
    // M4 (QA M4): `isConnected` is a PgSQLAdapter-only extension (not on the
    // base class nor on MySQLAdapter, which probes health through the C#
    // MySQL pool's Init path). We probe it best-effort when present so a
    // disconnected PG pool fails fast with a clear message; subclasses
    // without it are assumed connected after a successful Init.
    const adapterAny =
        /** @type {{ isConnected?: () => boolean }} */ (adapter);
    if (
        typeof adapterAny.isConnected === 'function' &&
        !adapterAny.isConnected()
    ) {
        throw new Error(
            `migrateSqliteToRemote: ${engine} backend is not connected. ` +
                'Check VRCX_Database.host/port/credentials and restart the app.'
        );
    }

    // `dstConfig` was removed from the signature (defect 3 fix). The
    // destination is exclusively the live singleton `adapter`; any candidate
    // target config the caller might supply could never override the
    // already-Init'd C# pool, so accepting it would risk silently routing the
    // migration to the wrong host. The UI guard `canMigrateToRemote` ensures
    // the running pool matches the user's intended target before we get here.

    // ── 1. Build source SQLite adapter (read-only) ───────────────────
    const srcAdapter = await createAdapter({ connection: srcConnStr });

    // M2 (QA M2 + Performance MEDIUM-1): cache source schema metadata
    // ONCE here. The previous copyTable implementation called
    // `srcAdapter.listTablesTypes()` per-table (38 tables → 1521 SQLite
    // queries / 2964 PG queries). This Map is reused by every copyTable
    // call AND by the user-table discovery loop below (§4), eliminating
    // the duplicate call that used to live at the top of §4.
    const srcSchema = await srcAdapter.listTablesTypes();
    const srcSchemaMap = new Map(srcSchema.map((t) => [t.tableName, t]));

    // ── 2. Ensure destination global schema exists ───────────────────
    await adapter.initGlobalSchema();

    // HIGH-2-perf (Performance HIGH-2): the copy pipeline below does NOT
    // wrap per-batch inserts in an explicit BEGIN/COMMIT transaction.
    // PgSQLAdapter.begin/commit/rollback each borrow a FRESH pooled
    // Npgsql connection, so a BEGIN on connection A cannot share its
    // transaction context with the INSERT on connection B that follows —
    // the transaction would silently no-op. Fixing this requires a C#
    // transaction API that holds a single connection across multiple
    // ExecuteNonQuery calls; that work is deferred beyond Phase 9.
    //
    // Consequence: every bulkInsert batch autocommits, costing 5-10×
    // throughput vs. a single wrapped transaction (PG fsync per batch).
    // This is an accepted known limitation for Phase 9 minimal scope.

    // ── 3. Migrate global tables (16, public schema) ─────────────────
    const globalTotal = GLOBAL_TABLES.length;
    let globalIdx = 0;
    for (const tableName of GLOBAL_TABLES) {
        globalIdx += 1;
        if (typeof onProgress === 'function') {
            onProgress({
                phase: 'global',
                table: tableName,
                current: globalIdx,
                total: globalTotal,
                rowsCopied
            });
        }
        try {
            const copied = await copyTable(
                srcAdapter,
                adapter,
                tableName, // SQLite flat name
                tableName, // PG public schema (search_path resolves it)
                batchSize,
                srcSchemaMap
            );
            rowsCopied += copied;
            globalTables += 1;
        } catch (err) {
            errors.push(
                `global:${tableName}: ${err.message || String(err)}`
            );
        }
    }

    // ── 4. Discover user tables from source SQLite ───────────────────
    // Group by prefix so we call `initUserSchema(prefix)` exactly once per
    // prefix, then copy each table under that prefix.
    //
    // M2: reuse `srcSchema` cached in §1 (no second listTablesTypes call).
    const tables = srcSchema;
    /** @type {Map<string, string[]>} prefix -> list of user-table base names */
    const userTablesByPrefix = new Map();

    for (const { tableName } of tables) {
        if (!tableName || GLOBAL_TABLES.includes(tableName)) continue;
        // SQLite internal tables (sqlite_*) are already filtered out by
        // listTablesTypes, but be defensive against `configs` etc.
        if (tableName === 'configs') continue;

        const match = matchUserTable(tableName);
        if (!match) continue;
        const { prefix, name } = match;
        if (!userTablesByPrefix.has(prefix)) {
            userTablesByPrefix.set(prefix, []);
        }
        userTablesByPrefix.get(prefix).push(name);
    }

    // ── 5. Migrate user tables per prefix ────────────────────────────
    const userTotal = Array.from(userTablesByPrefix.values()).reduce(
        (acc, arr) => acc + arr.length,
        0
    );
    let userIdx = 0;
    for (const [prefix, names] of userTablesByPrefix) {
        try {
            await adapter.initUserSchema(prefix);
        } catch (err) {
            errors.push(
                `user-schema:${prefix}: ${err.message || String(err)}`
            );
            continue;
        }

        for (const name of names) {
            userIdx += 1;
            const srcTable = `${prefix}_${name}`;
            const dstTable = adapter.userTable(prefix, name);
            if (typeof onProgress === 'function') {
                onProgress({
                    phase: 'user',
                    table: dstTable,
                    current: userIdx,
                    total: userTotal,
                    rowsCopied
                });
            }
            try {
                const copied = await copyTable(
                    srcAdapter,
                    adapter,
                    srcTable,
                    dstTable,
                    batchSize,
                    srcSchemaMap
                );
                rowsCopied += copied;
                userTables += 1;
            } catch (err) {
                errors.push(
                    `user:${dstTable}: ${err.message || String(err)}`
                );
            }
        }
    }

    return {
        globalTables,
        userTables,
        rowsCopied,
        errors
    };
}

/**
 * Match a flat SQLite table name against the 22 known user-table base names.
 *
 * A user table in SQLite is `${prefix}_${name}` where `name` is one of the 22
 * entries in `USER_TABLE_NAMES`. Because `name` itself may contain `_`
 * (e.g. `feed_gps`, `activity_sync_state_v2`), we try the longest base names
 * first so a shorter base name can't shadow a longer one.
 *
 * Returns `{ prefix, name }` or `null` if no known base name matches.
 *
 * @param {string} tableName - flat SQLite table name like `abc_feed_gps`.
 * @returns {{prefix: string, name: string}|null}
 */
function matchUserTable(tableName) {
    for (const name of USER_TABLE_NAMES_BY_LENGTH_DESC) {
        const suffix = '_' + name;
        if (tableName.endsWith(suffix)) {
            const prefix = tableName.slice(0, tableName.length - suffix.length);
            // Prefix must be non-empty and is the account hash (alnum +
            // leading underscore allowed — see `database.initUserTables`).
            if (prefix.length > 0) {
                return { prefix, name };
            }
            return null;
        }
    }
    return null;
}

/**
 * @typedef {import('./adapter/SQLiteAdapter.js').SQLiteAdapter | import('./adapter/PgSQLAdapter.js').PgSQLAdapter} AnyAdapter
 */

/**
 * Copy all rows from `srcTable` (SQLite) to `dstTable` (PG), in batches of
 * `batchSize`. Reads the source in paged `LIMIT/OFFSET` chunks and writes
 * each batch via `bulkInsert(..., 'ignore')` so memory stays bounded.
 *
 * M2 (Performance MEDIUM-1): column metadata is read from the caller-
 * supplied `srcSchemaMap` (cached once at the top of
 * `migrateSqliteToPgsql`) instead of re-querying `listTablesTypes()` per
 * table — eliminates 1521 SQLite / 2964 PG redundant queries across a
 * 38-table migration.
 *
 * HIGH-1-perf (Performance HIGH-1): the previous implementation called
 * `srcAdapter.select(srcTable, colList)` which materialises the ENTIRE
 * table into JS memory in one shot — a 500k-row table caused ~5-6×
 * memory放大 and risked OOM. `SQLiteAdapter.select` doesn't support
 * `OFFSET`, so we go through `srcAdapter.execute` directly with explicit
 * `LIMIT @limit OFFSET @offset` named params and stream rows page by
 * page. Both `SQLiteAdapter.execute` and `PgSQLAdapter.execute` receive
 * positional arrays from their C# `ExecuteJson` bridges, so `row[i]` is
 * the i-th selected column value (same access pattern as the H1/H2
 * fixes in PgSQLAdapter).
 *
 * Row-count verification: after the copy, `dst.count === src.count`. On
 * mismatch, an error is thrown (caught by the caller and recorded).
 *
 * @param {AnyAdapter} srcAdapter
 * @param {AnyAdapter} dstAdapter
 * @param {string} srcTable - source table identifier (SQLite flat).
 * @param {string} dstTable - destination table identifier (bare or `schema.name`).
 * @param {number} batchSize - rows per bulkInsert call.
 * @param {Map<string, {tableName: string, columns: Array<{name: string, isHidden: boolean}>}>} srcSchemaMap
 *   Cached source schema metadata (tableName → column descriptors).
 * @returns {Promise<number>} number of rows copied.
 */
async function copyTable(
    srcAdapter,
    dstAdapter,
    srcTable,
    dstTable,
    batchSize,
    srcSchemaMap
) {
    const tableMeta = srcSchemaMap.get(srcTable);
    if (!tableMeta) {
        // Source table doesn't exist (e.g. older DB without a later table).
        // Treat as 0-row copy rather than an error.
        return 0;
    }
    const visibleColumns = tableMeta.columns.filter((c) => !c.isHidden);
    if (visibleColumns.length === 0) return 0;
    const colList = visibleColumns.map((c) => c.name).join(', ');

    // Paged read: LIMIT/OFFSET loop. Memory stays O(batchSize) regardless
    // of source table size. `@limit` / `@offset` are named params handled
    // by SQLiteAdapter._normalizeArgs (source is always SQLite here).
    let offset = 0;
    let totalCopied = 0;
    while (true) {
        const batch = [];
        await srcAdapter.execute(
            (row) => {
                // row is a positional array in SELECT-column order
                // (C# ExecuteJson → object[][] → JSON.parse → array).
                const obj = {};
                visibleColumns.forEach((col, i) => {
                    obj[col.name] = row[i];
                });
                batch.push(obj);
            },
            `SELECT ${colList} FROM ${srcTable} LIMIT @limit OFFSET @offset`,
            { limit: batchSize, offset }
        );
        if (batch.length === 0) break;
        await dstAdapter.bulkInsert(dstTable, batch, 'ignore');
        offset += batch.length;
        totalCopied += batch.length;
        // Last page: fewer than batchSize rows → stop after this batch.
        if (batch.length < batchSize) break;
    }

    // Row-count verification per table.
    const srcCount = await srcAdapter.countWhere(srcTable);
    const dstCount = await dstAdapter.countWhere(dstTable);
    if (srcCount !== dstCount) {
        throw new Error(
            `row count mismatch after copy: src=${srcCount} dst=${dstCount}`
        );
    }

    return totalCopied;
}

export { GLOBAL_TABLES, USER_TABLE_NAMES };

/**
 * Backward-compatible alias for {@link migrateSqliteToRemote}. Kept so the
 * pre-merge PgSQL-only call site (`advanced.js` `migrateToPgsql`) and any
 * external callers/tests referencing the historical name keep working after
 * the engine-agnostic generalisation. The function body is identical:
 * `migrateSqliteToPgsql === migrateSqliteToRemote`.
 */
const migrateSqliteToPgsql = migrateSqliteToRemote;export { migrateSqliteToPgsql };
