// Phase 9 slice S9 (task 9.13) — SQLite → remote-engine cross-engine push.
//
// Provides `pushFromSqlite(srcConnStr, options)` which copies every
// global + user table from a source SQLite database into the currently
// initialised remote target (PostgreSQL or MySQL/MariaDB). The destination
// is the singleton `adapter` from `./adapter/index.js` — a `PgSQLAdapter`
// when `VRCX_Database.mode === 'postgresql'` or a `MySQLAdapter` when mode
// is `'mysql'`/`'mariadb'`, each saved + the app restarted so the C#
// `PostgreSQL.Instance` / `MySQL.Instance` pool is initialised before the
// renderer boots.
//
// The push body is engine-agnostic: it only touches the abstract
// `EngineAdapter` surface (`initGlobalSchema` / `initUserSchema` / `userTable`
// / `bulkInsert`), which every remote subclass implements, so the same code
// path serves both PG and MySQL destinations.
//
// NOTE: the destination is the live singleton only — there is no `dstConfig`
// parameter. Callers MUST ensure the engine has been switched + the app
// restarted so the singleton matches the user's intended target; the UI-side
// guard `canPushToRemote` in `stores/settings/advanced.js` enforces this by
// comparing the current UI refs against the boot-time config snapshot
// (`bootDbConfig` from `plugins/interopApi.js`). Passing a candidate target
// config here would be misleading: it could never override the already-Init'd
// C# pool, so any mismatch between the form and the running pool would silently
// route the push to the wrong host. See defect 3 (MEDIUM) fix.
//
// See `docs/PHASE9_PGSQL_DESIGN.md` §6.2 + §11.1 9.13 DoD.
//
// Design constraints honoured here (mirrors `pullEngine.js`):
//   - R6: `activity_sessions_v2` uses `GENERATED BY DEFAULT AS IDENTITY`, so
//     explicit `session_id` values copied from SQLite are accepted by PG.
//   - `id` / `session_id` columns are copied verbatim (SELECT * includes
//     them, bulkInsert writes them through).
//   - Errors per-GROUP are collected and the run continues — a single
//     broken group (global / per-prefix / mirror) does not abort the
//     whole push. Tables within a group share one transaction (atomic +
//     1 fsync per group instead of per-batch).
//   - Row-count verification per table; deeper sampling left to S12.
//   - DATA-INTEGRITY PRIORITY: the 18 global + 22 user base-name whitelists
//     cover the *known* schema, but the push MUST NOT silently drop tables
//     that fall outside them (upstream additions, legacy tables, etc.).
//     After the known tables are copied, every
//     remaining source table is mirrored into the destination: its column
//     metadata is read from PRAGMA `table_xinfo` and re-emitted as a
//     `CREATE TABLE IF NOT EXISTS` via the destination adapter's
//     `createTable` (which applies engine-specific type mapping), then the
//     rows are copied through the same paged `copyTable` path. Constraints
//     are mirrored at column-level only (single-col PK inline, composite PK
//     as a table-level `PRIMARY KEY(...)` clause; UNIQUE/indexes are NOT
//     re-created — recovery-time concerns). `configs` ∈ GLOBAL_TABLES, so it
//     is copied in §3 (the global group) under its original name:
//     `bulkInsert('ignore')` preserves the destination's pre-existing
//     `config:schema_version` (written by `runMigrations` before this
//     user-triggered push), so no boot-state pollution. Each mirrored table
//     in §6 is warn-logged so operators can see which tables the safety
//     net preserved.

import { adapter, createAdapter } from './adapter/index.js';

/**
 * 18 global tables (public schema) — mirrors `SQLiteAdapter.initGlobalSchema`
 * (L985-1049), `PgSQLAdapter.initGlobalSchema` (L1293-1341) and
 * `MySQLAdapter.initGlobalSchema` table-for-table. Order matches the
 * schema-init order so the push log reads naturally.
 * @type {string[]}
 */
const GLOBAL_TABLES = [
    'gamelog_location',
    'gamelog_join_leave',
    'gamelog_portal_spawn',
    'gamelog_video_play',
    'gamelog_resource_load',
    'gamelog_event',
    'gamelog_external',
    'cache_avatar',
    'cache_world',
    'favorite_world',
    'favorite_avatar',
    'favorite_friend',
    'memos',
    'world_memos',
    'avatar_memos',
    'avatar_tags',
    'cookies',
    'configs'
];

/**
 * 22 user-table base names — mirrors `PgSQLAdapter.initUserSchema` (L1133-1206)
 * / `SQLiteAdapter.initUserSchema` (L900-979) / `MySQLAdapter.initUserSchema`.
 * In the source SQLite DB these live flat as `${prefix}_${name}`; in a
 * destination PG DB they live in the `account_${prefix}` schema as just
 * `${name}`, and in a destination MySQL DB they live as the prefixed name
 * `${prefix}_${name}` (see `userTable(prefix, name)` — each adapter resolves
 * the destination identifier itself, so this list is engine-agnostic).
 *
 * Sorted longest-first when matching so e.g. `activity_sync_state_v2` is tried
 * before `activity_sessions_v2` (no overlap here, but the rule is defensive
 * against future additions).
 * @type {string[]}
 */
const USER_TABLE_NAMES = [
    'activity_bucket_cache_v2',
    'activity_sync_state_v2',
    'activity_sessions_v2',
    'manual_relations_MANUEL',
    'mutual_graph_friends_old',
    'mutual_graph_links_old',
    'mutual_graph_friends',
    'mutual_graph_links',
    'mutual_graph_meta',
    'feed_online_offline',
    'friend_log_current',
    'friend_log_history',
    'tracked_nonfriends',
    'notifications_v2',
    'notifications',
    'avatar_history',
    'feed_status',
    'feed_avatar',
    'feed_gps',
    'feed_bio',
    'moderation',
    'notes'
];

// Longest-first for `endsWith('_' + name)` matching.
const USER_TABLE_NAMES_BY_LENGTH_DESC = [...USER_TABLE_NAMES].sort(
    (a, b) => b.length - a.length
);

/**
 * @typedef {Object} PushProgress
 * @property {'global'|'user'|'mirror'} phase
 * @property {string} table - destination table identifier (bare name or `account_{prefix}.{name}`)
 * @property {number} current - 1-based index of the current table within its phase
 * @property {number} total - total tables in this phase
 * @property {number} rowsCopied - running total rows copied across all tables so far
 */

/**
 * @typedef {Object} PushResult
 * @property {number} globalTables - fixed whitelist iteration count, always 18 (source-missing tables still count as 0-row copies); unlike pull's "actually-enumerated whitelist count (≤18)" semantics
 * @property {number} userTables - number of known user tables processed (across all prefixes)
 * @property {number} unknownTables - number of non-whitelist tables mirrored + copied (data-integrity safety net)
 * @property {number} rowsCopied - total rows copied
 * @property {string[]} errors - per-table error messages (empty on full success)
 */

/**
 * Push data from a SQLite database to a remote-engine target
 * (PostgreSQL or MySQL/MariaDB).
 *
 * The destination is, by default, the singleton `adapter` from
 * `./adapter/index.js`, which is a `PgSQLAdapter` when the app booted with
 * `VRCX_Database.mode === 'postgresql'` (C# `PostgreSQL` pool initialised)
 * or a `MySQLAdapter` when mode is `'mysql'`/`'mariadb'` (C# `MySQL`
 * initialised). In this mode callers must ensure the engine has been switched
 * + the app restarted before invoking this function; otherwise the
 * destination writes would go to the live SQLite adapter and corrupt it.
 * We guard against this by refusing to run when the singleton's `engineType`
 * is `'sqlite'` (or the abstract `'unknown'`).
 *
 * When `options.dstAdapter` is provided, ALL writes are routed to that
 * adapter instance instead of the singleton. This enables ad-hoc migration:
 * a fresh adapter is constructed from form fields on the caller side (see
 * `advanced.js`) and passed through, bypassing the boot-time C# pool
 * entirely. The singleton engine-type and liveness guards are skipped in
 * this mode — the caller is responsible for providing a properly-
 * initialised destination adapter.
 *
 * The body is engine-agnostic: it only touches abstract `EngineAdapter`
 * methods every remote subclass implements, so PG and MySQL share one code
 * path. `isConnected` (a PgSQLAdapter extension) is probed best-effort when
 * present; subclasses without it are assumed connected after a successful Init.
 *
 * There is intentionally NO `dstConfig` parameter: the destination is either
 * the live singleton (legacy mode) or a caller-supplied adapter instance
 * (`dstAdapter`). Accepting a candidate config string would let a caller
 * pass values that disagree with the running pool, creating the illusion
 * that the push honours them while it actually writes to the boot-time
 * connection (defect 3). The caller-side guard `canPushToRemote` blocks
 * that case before invoking this function.
 *
 * @param {string} srcConnStr - SQLite connection string like 'sqlite:///C:/path/to/old.db'.
 * @param {object} [options] - Optional { batchSize=500, onProgress?, dstAdapter? }.
 * @param {number} [options.batchSize=500] - rows per bulkInsert call (PG param limit 65535; 500 rows × ~50 cols is safe; MySQL prepared-statement limit is similar).
 * @param {(p: PushProgress) => void} [options.onProgress] - progress callback for UI.
 * @param {import('./adapter/EngineAdapter.js').EngineAdapter} [options.dstAdapter] - ad-hoc destination adapter. When present, ALL writes go to this instance instead of the singleton `adapter`, and the engine-type + liveness guards are skipped. The caller is responsible for initialisation and teardown.
 * @returns {Promise<PushResult>}
 */
export async function pushFromSqlite(
    srcConnStr,
    options = {}
) {
    const { batchSize = 500, onProgress, dstAdapter } = options;
    const dst = dstAdapter ?? adapter;
    const errors = [];
    let rowsCopied = 0;
    let globalTables = 0;
    let userTables = 0;
    let unknownTables = 0;

    // ── 0. Guards ────────────────────────────────────────────────────
    // The destination must NOT be a SQLiteAdapter. If it is, the user
    // hasn't switched engine + restarted yet — refuse to run rather than
    // silently corrupt the live SQLite database.
    //
    // When `dstAdapter` is provided (ad-hoc mode), the engine and
    // liveness checks are skipped — the caller is responsible for
    // providing a properly-initialised adapter. Ad-hoc adapters are
    // constructed on the caller side (see `advanced.js`), bypassing the
    // boot-time C# pool, so no singleton guard is needed.
    //
    // Original M1 fix (QA M1 + Security M1) used `dropUserSchema` as a
    // PgSQLAdapter-only discriminator, but that made the push
    // Pg-only and excluded MySQLAdapter (which deliberately has no
    // `dropUserSchema` because MySQL stores user tables flat under a
    // `prefix_` naming scheme rather than in per-account schemas). To treat
    // both remote engines uniformly we now gate on `adapter.engineType` —
    // an abstract getter every subclass overrides — and accept any value
    // that isn't `'sqlite'` (or the abstract default `'unknown'`).
    if (!dstAdapter) {
        const engine =
            /** @type {{ engineType?: string, isConnected?: () => Promise<boolean> }} */ (
                adapter
            ).engineType;
        if (!engine || engine === 'sqlite' || engine === 'unknown') {
            throw new Error(
                'pushFromSqlite: destination adapter is the default SQLite engine. ' +
                    'Switch VRCX_Database.mode to "postgresql", "mysql" or "mariadb" and ' +
                    'restart the app before running the push.'
            );
        }
        // `isConnected` is a real liveness probe (`SELECT 1`) on both
        // PgSQLAdapter and MySQLAdapter — resolves true when the backend is
        // reachable, false (or absent on SQLite) when not. We probe it
        // best-effort when present so a disconnected remote backend fails
        // fast with a clear message before starting the long copy.
        const adapterAny =
            /** @type {{ isConnected?: () => Promise<boolean> }} */ (adapter);
        if (
            typeof adapterAny.isConnected === 'function' &&
            !await adapterAny.isConnected()
        ) {
            throw new Error(
                `pushFromSqlite: ${engine} backend is not connected. ` +
                    'Check VRCX_Database.host/port/credentials and restart the app.'
            );
        }
    }

    // `dstConfig` was removed from the signature (defect 3 fix). The
    // `dstAdapter` option replaces it with a different contract: instead
    // of a config object that could never override the C# pool, callers
    // may now pass a fully-constructed adapter instance. When `dstAdapter`
    // is provided, the singleton engine-type + liveness guards are skipped
    // and all writes go to the ad-hoc adapter. When absent (legacy/singleton
    // mode), the behaviour is unchanged — the boot-time singleton `adapter`
    // is used, protected by the engine-type guard above and the UI-side
    // `canPushToRemote` guard in `stores/settings/advanced.js`.

    // ── 1. Build source SQLite adapter (read-only) ───────────────────
    const srcAdapter = await createAdapter({ connection: srcConnStr });

    // M2 (QA M2 + Performance MEDIUM-1): cache source schema metadata
    // ONCE here. The previous copyTable implementation called
    // `srcAdapter.listTablesTypes()` per-table (38 tables → 1521 SQLite
    // queries / 2964 PG queries). This Map is reused by every copyTable
    // call AND by the user-table discovery loop below (§4), eliminating
    // the duplicate call that used to live at the top of §4.
    const srcSchema = await srcAdapter.listTablesTypes();
    const srcSchemaMap = new Map(srcSchema.map((t) => [t.tableName, t]));

    // ── 2. Ensure destination global schema exists ───────────────────
    await dst.initGlobalSchema();

    // ── 3. Push global tables (18, public schema) ─────────────────
    // 整组包一个事务:18 张全局表要么全成功要么全回滚,1 次 fsync。
    const globalTotal = GLOBAL_TABLES.length;
    let globalIdx = 0;
    try {
        await dst.withTransaction(async () => {
            for (const tableName of GLOBAL_TABLES) {
                globalIdx += 1;
                if (typeof onProgress === 'function') {
                    onProgress({
                        phase: 'global',
                        table: tableName,
                        current: globalIdx,
                        total: globalTotal,
                        rowsCopied
                    });
                }
                const copied = await copyTable(
                    srcAdapter,
                    dst,
                    tableName,
                    tableName,
                    batchSize,
                    srcSchemaMap
                );
                rowsCopied += copied;
                globalTables += 1;
            }
        });
    } catch (err) {
        errors.push(`global-group: ${err.message || String(err)}`);
    }

    // ── 4. Discover user tables + unknown tables from source SQLite ──
    // Known user tables are grouped by prefix so `initUserSchema(prefix)`
    // runs once per prefix. Tables that match NEITHER the 18 global names
    // NOR any of the 22 user base-name suffixes are collected separately as
    // "unknown" — they are mirrored + copied in §6 so no source data is
    // silently dropped (data-integrity priority). `sqlite_*` are already
    // excluded by `listTablesTypes`; `configs` needs no special-casing here:
    // it is a member of `GLOBAL_TABLES` (see §3), so this loop skips it —
    // the global group copies it with `bulkInsert('ignore')`, preserving any
    // keys the new engine already wrote (e.g. `config:schema_version`).
    //
    // M2: reuse `srcSchema` cached in §1 (no second listTablesTypes call).
    const tables = srcSchema;
    /** @type {Map<string, string[]>} prefix -> list of user-table base names */
    const userTablesByPrefix = new Map();
    /** @type {string[]} non-whitelist table names to mirror in §6 */
    const unknownTableNames = [];

    for (const { tableName } of tables) {
        if (!tableName || GLOBAL_TABLES.includes(tableName)) continue;

        const match = matchUserTable(tableName);
        if (match) {
            const { prefix, name } = match;
            if (!userTablesByPrefix.has(prefix)) {
                userTablesByPrefix.set(prefix, []);
            }
            userTablesByPrefix.get(prefix).push(name);
        } else {
            // Unknown table (legacy, upstream-added, configs, ...) — mirror.
            unknownTableNames.push(tableName);
        }
    }

    // ── 5. Push user tables per prefix ────────────────────────────
    // 每个 prefix 包一个事务:同账户的 22 张表原子,失败回滚该账户,
    // 其他账户保留。initUserSchema 在事务内(DDL 在 PG 事务中可回滚)。
    const userTotal = Array.from(userTablesByPrefix.values()).reduce(
        (acc, arr) => acc + arr.length,
        0
    );
    let userIdx = 0;
    for (const [prefix, names] of userTablesByPrefix) {
        try {
            await dst.withTransaction(async () => {
                await dst.initUserSchema(prefix);
                for (const name of names) {
                    userIdx += 1;
                    const srcTable = `${prefix}_${name}`;
                    const dstTable = dst.userTable(prefix, name);
                    if (typeof onProgress === 'function') {
                        onProgress({
                            phase: 'user',
                            table: dstTable,
                            current: userIdx,
                            total: userTotal,
                            rowsCopied
                        });
                    }
                    const copied = await copyTable(
                        srcAdapter,
                        dst,
                        srcTable,
                        dstTable,
                        batchSize,
                        srcSchemaMap
                    );
                    rowsCopied += copied;
                    userTables += 1;
                }
            });
        } catch (err) {
            errors.push(
                `user-group:${prefix}: ${err.message || String(err)}`
            );
        }
    }

    // ── 6. Mirror + copy unknown tables (data-integrity safety net) ───
    // Every source table not covered by the known global/user schema is
    // recreated on the destination from its PRAGMA `table_xinfo` column
    // metadata (column-level PK + engine type mapping only; UNIQUE/indexes
    // are NOT re-created) then copied through the same paged `copyTable`.
    //
    // Each mirrored table is warn-logged so operators can see which tables
    // fell outside the known schema (upstream additions, legacy tables) and
    // were preserved by the safety net rather than dropped.
    if (unknownTableNames.length > 0) {
        console.warn(
            `[迁移] 发现 ${unknownTableNames.length} 张非白名单表，将镜像保底复制: ` +
                unknownTableNames.join(', ')
        );
    }
    const mirrorTotal = unknownTableNames.length;
    let mirrorIdx = 0;
    try {
        await dst.withTransaction(async () => {
            for (const srcTable of unknownTableNames) {
                mirrorIdx += 1;
                const dstTable = srcTable;
                if (typeof onProgress === 'function') {
                    onProgress({
                        phase: 'mirror',
                        table: dstTable,
                        current: mirrorIdx,
                        total: mirrorTotal,
                        rowsCopied
                    });
                }
                const colDefs = buildMirroredColumns(
                    srcSchemaMap.get(srcTable)
                );
                if (colDefs.length > 0) {
                    await dst.createTable(dstTable, colDefs);
                }
                const copied = await copyTable(
                    srcAdapter,
                    dst,
                    srcTable,
                    dstTable,
                    batchSize,
                    srcSchemaMap
                );
                rowsCopied += copied;
                unknownTables += 1;
            }
        });
    } catch (err) {
        errors.push(`mirror-group: ${err.message || String(err)}`);
    }

    return {
        globalTables,
        userTables,
        unknownTables,
        rowsCopied,
        errors
    };
}

/**
 * Match a flat SQLite table name against the 22 known user-table base names.
 *
 * A user table in SQLite is `${prefix}_${name}` where `name` is one of the 22
 * entries in `USER_TABLE_NAMES`. Because `name` itself may contain `_`
 * (e.g. `feed_gps`, `activity_sync_state_v2`), we try the longest base names
 * first so a shorter base name can't shadow a longer one.
 *
 * Returns `{ prefix, name }` or `null` if no known base name matches.
 *
 * @param {string} tableName - flat SQLite table name like `abc_feed_gps`.
 * @returns {{prefix: string, name: string}|null}
 */
function matchUserTable(tableName) {
    for (const name of USER_TABLE_NAMES_BY_LENGTH_DESC) {
        const suffix = '_' + name;
        if (tableName.endsWith(suffix)) {
            const prefix = tableName.slice(0, tableName.length - suffix.length);
            // Prefix must be non-empty and is the account hash (alnum +
            // leading underscore allowed — see `database.initUserTables`).
            if (prefix.length > 0) {
                return { prefix, name };
            }
            return null;
        }
    }
    return null;
}

/**
 * Copy all rows from `srcTable` (SQLite) to `dstTable` (PG), in batches of
 * `batchSize`. Reads the source in paged `LIMIT/OFFSET` chunks and writes
 * each batch via `bulkInsert(..., 'ignore')` so memory stays bounded.
 *
 * M2 (Performance MEDIUM-1): column metadata is read from the caller-
 * supplied `srcSchemaMap` (cached once at the top of
 * `pushFromSqlite`) instead of re-querying `listTablesTypes()` per
 * table — eliminates 1521 SQLite / 2964 PG redundant queries across a
 * 38-table push.
 *
 * HIGH-1-perf (Performance HIGH-1): the previous implementation called
 * `srcAdapter.select(srcTable, colList)` which materialises the ENTIRE
 * table into JS memory in one shot — a 500k-row table caused ~5-6×
 * memory放大 and risked OOM. `SQLiteAdapter.select` doesn't support
 * `OFFSET`, so we go through `srcAdapter.execute` directly with explicit
 * `LIMIT @limit OFFSET @offset` named params and stream rows page by
 * page. Both `SQLiteAdapter.execute` and `PgSQLAdapter.execute` receive
 * positional arrays from their C# `ExecuteJson` bridges, so `row[i]` is
 * the i-th selected column value (same access pattern as the H1/H2
 * fixes in PgSQLAdapter).
 *
 * Row-count verification: after the copy, `dst.count === src.count`. On
 * mismatch, an error is thrown (caught by the caller and recorded).
 *
 * @param {import('./adapter/EngineAdapter.js').EngineAdapter} srcAdapter
 * @param {import('./adapter/EngineAdapter.js').EngineAdapter} dstAdapter
 * @param {string} srcTable - source table identifier (SQLite flat).
 * @param {string} dstTable - destination table identifier (bare or `schema.name`).
 * @param {number} batchSize - rows per bulkInsert call.
 * @param {Map<string, {tableName: string, columns: Array<{name: string, isHidden: boolean}>}>} srcSchemaMap
 *   Cached source schema metadata (tableName → column descriptors).
 * @returns {Promise<number>} number of rows copied.
 */
async function copyTable(
    srcAdapter,
    dstAdapter,
    srcTable,
    dstTable,
    batchSize,
    srcSchemaMap
) {
    const tableMeta = srcSchemaMap.get(srcTable);
    if (!tableMeta) {
        // Source table doesn't exist (e.g. older DB without a later table).
        // Treat as 0-row copy rather than an error.
        return 0;
    }
    const visibleColumns = tableMeta.columns.filter((c) => !c.isHidden);
    if (visibleColumns.length === 0) return 0;
    // MySQL 目标侧列名(key 是 MySQL 保留字)需反引号转义;此处为对称防御,
    // 实际 push 源恒为 SQLite(无 quoteIdent → 回退裸名,key 在 SQLite 合法)。
    const srcQuoteIdent =
        /** @type {{ quoteIdent?: (name: string) => string } | null} */ (
            srcAdapter
        ).quoteIdent;
    const quote = (name) => srcQuoteIdent?.(name) ?? name;
    const colList = visibleColumns.map((c) => quote(c.name)).join(', ');

    // ── 游标分页(keyset pagination)─────────────────────────────────
    // 旧实现用 LIMIT/OFFSET,OFFSET 是"扫描并丢弃",第 N 页扫描
    // N×batchSize 行,O(N²) 复杂度。50 万行表分 1000 页,末页扫描 50
    // 万行。改用 WHERE pk > @lastPk ORDER BY pk LIMIT @limit,O(N) 复杂度。
    //
    // 前提:表有单列 PK(整数或文本),可用作稳定游标。复合 PK 或无 PK
    // 表退回 OFFSET 模式(安全兜底)。
    const pkCols = visibleColumns.filter((c) => c.isPK);
    const useCursor = pkCols.length === 1;
    const pkCol = useCursor ? pkCols[0].name : null;

    let lastPk = null;
    let offset = 0;
    let totalCopied = 0;
    // 复制前快照目标行数:目标可能预存引擎写入的行(如 configs 的
    // schema_version 检查点),这些计入 dstBefore,严格相等校验得以保留。
    const dstBefore = await dstAdapter.countWhere(dstTable);
    let actualInserted = 0;
    while (true) {
        const batch = [];
        let sql;
        let params;
        if (useCursor) {
            if (lastPk === null) {
                sql = `SELECT ${colList} FROM ${srcTable} ORDER BY ${quote(pkCol)} LIMIT @limit`;
                params = { limit: batchSize };
            } else {
                sql = `SELECT ${colList} FROM ${srcTable} WHERE ${quote(pkCol)} > @lastPk ORDER BY ${quote(pkCol)} LIMIT @limit`;
                params = { limit: batchSize, lastPk };
            }
        } else {
            sql = `SELECT ${colList} FROM ${srcTable} LIMIT @limit OFFSET @offset`;
            params = { limit: batchSize, offset };
        }
        await srcAdapter.execute(
            (row) => {
                // row is a positional array in SELECT-column order
                // (C# ExecuteJson → object[][] → JSON.parse → array).
                const obj = {};
                visibleColumns.forEach((col, i) => {
                    // DBNull 经 C# 封送/JSON 序列化为 null/undefined,统一
                    // 兜底为 null,避免 undefined 作为参数传回 C# 时被跳过
                    // (MySqlConnector: "Parameter '@x' must be defined")。
                    obj[col.name] = row[i] ?? null;
                });
                batch.push(obj);
            },
            sql,
            params
        );
        if (batch.length === 0) break;
        // bulkInsert 透传 executeNonQuery 的 affected rows(INSERT IGNORE
        // 跳过的冲突行不计入),累加真实写入量供循环后严格校验。
        actualInserted += await dstAdapter.bulkInsert(dstTable, batch, 'ignore');
        totalCopied += batch.length;
        if (useCursor) {
            // 更新游标:取本批最后一行的 PK 值
            const lastRow = batch[batch.length - 1];
            lastPk = lastRow[pkCol];
        } else {
            offset += batch.length;
        }
        // Last page: fewer than batchSize rows → stop after this batch.
        if (batch.length < batchSize) break;
    }

    // Row-count verification:严格相等校验,但把目标预存行(dstBefore)与
    // 实际写入行(actualInserted)分开计算——configs 的 schema_version
    // 检查点等预存行计入 dstBefore,不再误报;而批量写失败被吞、
    // IGNORE 跳过超预期这类真实丢数据仍会被 dstCount != 期望值抓住。
    // 代价:每表多一次 COUNT(dstBefore);推送目标通常无并发写,可接受。
    const dstCount = await dstAdapter.countWhere(dstTable);
    if (dstCount !== dstBefore + actualInserted) {
        throw new Error(
            `row count mismatch after copy: copied=${totalCopied} ` +
                `dst=${dstCount} dstBefore=${dstBefore} actualInserted=${actualInserted}`
        );
    }

    return totalCopied;
}

/**
 * Build structured column definitions for mirroring an unknown source table
 * onto the destination via `adapter.createTable`.
 *
 * Reads the cached PRAGMA `table_xinfo` descriptor and produces
 * `{ name, type, constraints? }` objects (plus, for composite PKs, a trailing
 * raw `PRIMARY KEY(...)` string entry) that every adapter's `createTable`
 * accepts. Engine-specific type mapping is delegated to the destination
 * adapter's `_mapColumnType` (PG: INTEGER PK → BIGINT GENERATED BY DEFAULT AS
 * IDENTITY; MySQL: INTEGER → INT, TEXT PK → VARCHAR(255)).
 *
 * Scope (per data-integrity decision): column-level PK + type mapping only.
 * `isHidden` columns (SQLite generated/virtual) are excluded from both the
 * DDL and the copied rows. UNIQUE constraints and secondary indexes are NOT
 * re-created — they are recovery-time concerns, not data-preservation ones.
 *
 * @param {{tableName: string, columns: Array<{name: string, type: string, notNull: boolean, defaultValue: *, isPK: boolean, isHidden: boolean}>}|undefined} tableMeta
 *   Cached source schema metadata for the table (from `srcSchemaMap`).
 * @returns {object[]} column defs for `adapter.createTable` — `{name,type,constraints?}`
 *   objects, optionally followed by a raw `PRIMARY KEY (...)` string for
 *   composite PKs (runtime `createTable` already handles `typeof col ===
 *   'string'` entries; the declared return type stays `object[]` to match the
 *   base-class signature without modifying it). Empty array if the table has
 *   no visible columns or no metadata.
 */
function buildMirroredColumns(tableMeta) {
    if (!tableMeta || !Array.isArray(tableMeta.columns)) return [];
    const visible = tableMeta.columns.filter((c) => !c.isHidden);
    if (visible.length === 0) return [];
    const pkCols = visible.filter((c) => c.isPK).map((c) => c.name);
    /** @type {object[]} */
    const cols = visible.map((c) => {
        /** @type {string[]} */
        const cons = [];
        if (c.notNull) cons.push('NOT NULL');
        if (c.defaultValue != null && c.defaultValue !== '') {
            const dv = c.defaultValue;
            if (typeof dv === 'object') {
                cons.push(
                    `DEFAULT '${JSON.stringify(dv).replace(/'/g, "''")}'`
                );
            } else if (typeof dv === 'number' || typeof dv === 'boolean') {
                cons.push(`DEFAULT ${dv}`);
            } else {
                cons.push(
                    `DEFAULT '${String(dv).replace(/'/g, "''")}'`
                );
            }
        }
        // Inline PRIMARY KEY only for single-column PKs; composite PKs are
        // emitted as a table-level clause below.
        if (pkCols.length === 1 && c.isPK) cons.push('PRIMARY KEY');
        /** @type {{name: string, type: string, constraints?: string}} */
        const def = { name: c.name, type: c.type || 'TEXT' };
        if (cons.length > 0) def.constraints = cons.join(' ');
        return def;
    });
    if (pkCols.length > 1) {
        // Table-level composite PK appended as a raw string entry; every
        // adapter's `createTable` passes `typeof col === 'string'` entries
        // through verbatim (PG `_mapColumnType` leaves `PRIMARY KEY (...)`
        // untouched — no INTEGER/TEXT token to rewrite — and MySQL/SQLite
        // return the string as-is). Cast through `unknown` so `cols`
        // (declared `object[]` to match the base-class signature, which is
        // NOT modified) accepts the raw string.
        cols.push(
            /** @type {object} */ (
                /** @type {unknown} */ (`PRIMARY KEY (${pkCols.join(', ')})`)
            )
        );
    }
    return cols;
}

export { GLOBAL_TABLES, USER_TABLE_NAMES };
