-- ============================================================================
-- CI seed data -- PostgreSQL dialect
-- ============================================================================
-- 镜像源:src/services/database/adapter/PgSQLAdapter.js
--   initGlobalSchema  L1435-1534(18 张全局表,public. 限定)
--   initUserSchema    L1275-1401 (22 张用户表,account_abc. 限定)
-- 同步义务:本文件 DDL 必须与 adapter 源码逐字一致(列名/类型/NOT NULL/
--   DEFAULT/主键/唯一约束/列顺序)。修改 adapter 建表语句时必须同步更新本文件。
-- 幂等策略:DDL 用 CREATE TABLE IF NOT EXISTS;DML 用
--   INSERT ... ON CONFLICT (该表完整主键列) DO NOTHING,整个文件可重复执行。
--   索引用 CREATE INDEX IF NOT EXISTS,名称与 adapter 完全一致。
-- 方言注意事项:
--   - 全局表显式 public. 限定,用户表 account_abc. 限定;用户表前先建 schema。
--   - 自增列为 BIGINT GENERATED BY DEFAULT AS IDENTITY,可显式插入 id。
--   - cookies/configs 的 key 非保留字,裸写。
--   - activity_bucket_cache_v2 的 json 列有 DEFAULT '[]'/'[]'/'{}',但按
--     镜像规则仍显式赋值;ascii 列仅填 ASCII 值。
--   - gamelog_event / gamelog_external 的 UNIQUE 约束不带前缀长度
--     (PG 的 TEXT 可直接建唯一索引),种子值均 < 100 字符。
--   - 9 个 CREATE INDEX IF NOT EXISTS:4 个用户表索引(镜像 L1350-1361)
--     + 5 个全局表索引(镜像 L1498-1512),名称与 adapter 完全一致。
--   - 末尾 setval 同步块:本文件全部显式插入 identity 主键 id,而 PG 的
--     GENERATED BY DEFAULT AS IDENTITY 不会随显式插入推进底层序列(MySQL
--     InnoDB 会自动抬升 auto_increment,PG 不会),故在全部 DML 之后对 17 张
--     identity PK 表执行 setval(pg_get_serial_sequence(...), MAX(id)),
--     确保后续无显式 id 的 INSERT 不会撞主键。该块同样幂等,可重复执行。
-- 章节:1. Global DDL -> 2. User DDL -> 3. Global DML -> 4. User DML -> 5. Identity sequence sync
-- 数据规划:22 行 global + 29 行 user(逐表行数见各表注释),满足 CI smoke 计数断言。
-- ============================================================================

-- ── 1. Global DDL(18 tables, schema public, mirrored from initGlobalSchema L1435-1534) ──

CREATE TABLE IF NOT EXISTS public.gamelog_location (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, location TEXT, world_id TEXT, world_name TEXT, time BIGINT, group_name TEXT, UNIQUE(created_at, location));
CREATE TABLE IF NOT EXISTS public.gamelog_join_leave (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, type TEXT, display_name TEXT, location TEXT, user_id TEXT, time BIGINT, UNIQUE(created_at, type, display_name));
CREATE TABLE IF NOT EXISTS public.gamelog_portal_spawn (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, display_name TEXT, location TEXT, user_id TEXT, instance_id TEXT, world_name TEXT, UNIQUE(created_at, display_name));
CREATE TABLE IF NOT EXISTS public.gamelog_video_play (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, video_url TEXT, video_name TEXT, video_id TEXT, location TEXT, display_name TEXT, user_id TEXT, UNIQUE(created_at, video_url));
CREATE TABLE IF NOT EXISTS public.gamelog_resource_load (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, resource_url TEXT, resource_type TEXT, location TEXT, UNIQUE(created_at, resource_url));
CREATE TABLE IF NOT EXISTS public.gamelog_event (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, data TEXT, UNIQUE(created_at, data));
CREATE TABLE IF NOT EXISTS public.gamelog_external (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, message TEXT, display_name TEXT, user_id TEXT, location TEXT, UNIQUE(created_at, message));
CREATE TABLE IF NOT EXISTS public.cache_avatar (id TEXT PRIMARY KEY, added_at TEXT, author_id TEXT, author_name TEXT, created_at TEXT, description TEXT, image_url TEXT, name TEXT, release_status TEXT, thumbnail_image_url TEXT, updated_at TEXT, version BIGINT);
CREATE TABLE IF NOT EXISTS public.cache_world (id TEXT PRIMARY KEY, added_at TEXT, author_id TEXT, author_name TEXT, created_at TEXT, description TEXT, image_url TEXT, name TEXT, release_status TEXT, thumbnail_image_url TEXT, updated_at TEXT, version BIGINT);
CREATE TABLE IF NOT EXISTS public.favorite_world (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, world_id TEXT, group_name TEXT);
CREATE TABLE IF NOT EXISTS public.favorite_avatar (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, avatar_id TEXT, group_name TEXT);
CREATE TABLE IF NOT EXISTS public.favorite_friend (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, user_id TEXT, group_name TEXT);
CREATE TABLE IF NOT EXISTS public.memos (user_id TEXT PRIMARY KEY, edited_at TEXT, memo TEXT);
CREATE TABLE IF NOT EXISTS public.world_memos (world_id TEXT PRIMARY KEY, edited_at TEXT, memo TEXT);
CREATE TABLE IF NOT EXISTS public.avatar_memos (avatar_id TEXT PRIMARY KEY, edited_at TEXT, memo TEXT);
CREATE TABLE IF NOT EXISTS public.avatar_tags (avatar_id TEXT NOT NULL, tag TEXT NOT NULL, color TEXT, PRIMARY KEY (avatar_id, tag));
CREATE TABLE IF NOT EXISTS public.cookies (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS public.configs (key TEXT PRIMARY KEY, value TEXT);

-- Global indexes(5, mirrored from initGlobalSchema L1498-1512)
CREATE INDEX IF NOT EXISTS gamelog_location_created_at_idx ON public.gamelog_location (created_at);
CREATE INDEX IF NOT EXISTS idx_gamelog_location_world_created ON public.gamelog_location (world_id, created_at);
CREATE INDEX IF NOT EXISTS idx_gamelog_jl_location ON public.gamelog_join_leave (location);
CREATE INDEX IF NOT EXISTS idx_gamelog_jl_user_created ON public.gamelog_join_leave (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_gamelog_jl_display_created ON public.gamelog_join_leave (display_name, created_at);

-- ── 2. User DDL(22 tables, schema account_abc, mirrored from initUserSchema L1275-1401) ──

CREATE SCHEMA IF NOT EXISTS account_abc;

CREATE TABLE IF NOT EXISTS account_abc.feed_gps (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, user_id TEXT, display_name TEXT, location TEXT, world_name TEXT, previous_location TEXT, time BIGINT, group_name TEXT);
CREATE TABLE IF NOT EXISTS account_abc.feed_status (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, user_id TEXT, display_name TEXT, status TEXT, status_description TEXT, previous_status TEXT, previous_status_description TEXT);
CREATE TABLE IF NOT EXISTS account_abc.feed_bio (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, user_id TEXT, display_name TEXT, bio TEXT, previous_bio TEXT);
CREATE TABLE IF NOT EXISTS account_abc.feed_avatar (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, user_id TEXT, display_name TEXT, owner_id TEXT, avatar_name TEXT, current_avatar_image_url TEXT, current_avatar_thumbnail_image_url TEXT, previous_current_avatar_image_url TEXT, previous_current_avatar_thumbnail_image_url TEXT);
CREATE TABLE IF NOT EXISTS account_abc.feed_online_offline (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, user_id TEXT, display_name TEXT, type TEXT, location TEXT, world_name TEXT, time BIGINT, group_name TEXT);
CREATE TABLE IF NOT EXISTS account_abc.activity_sync_state_v2 (user_id TEXT PRIMARY KEY, updated_at TEXT NOT NULL DEFAULT '', is_self BIGINT NOT NULL DEFAULT 0, source_last_created_at TEXT NOT NULL DEFAULT '', pending_session_start_at BIGINT, cached_range_days BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS account_abc.activity_sessions_v2 (session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT NOT NULL, start_at BIGINT NOT NULL, end_at BIGINT NOT NULL, is_open_tail BIGINT NOT NULL DEFAULT 0, source_revision TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS account_abc.activity_bucket_cache_v2 (user_id TEXT NOT NULL, target_user_id TEXT NOT NULL DEFAULT '', range_days BIGINT NOT NULL, view_kind TEXT NOT NULL, exclude_key TEXT NOT NULL DEFAULT '', bucket_version BIGINT NOT NULL DEFAULT 1, raw_buckets_json TEXT NOT NULL DEFAULT '[]', normalized_buckets_json TEXT NOT NULL DEFAULT '[]', built_from_cursor TEXT NOT NULL DEFAULT '', summary_json TEXT NOT NULL DEFAULT '{}', built_at TEXT NOT NULL DEFAULT '', PRIMARY KEY (user_id, target_user_id, range_days, view_kind, exclude_key));
CREATE TABLE IF NOT EXISTS account_abc.friend_log_current (user_id TEXT PRIMARY KEY, display_name TEXT, trust_level TEXT, friend_number BIGINT);
CREATE TABLE IF NOT EXISTS account_abc.friend_log_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT, type TEXT, user_id TEXT, display_name TEXT, previous_display_name TEXT, trust_level TEXT, previous_trust_level TEXT, friend_number BIGINT);
CREATE TABLE IF NOT EXISTS account_abc.notifications (id TEXT PRIMARY KEY, created_at TEXT, type TEXT, sender_user_id TEXT, sender_username TEXT, receiver_user_id TEXT, message TEXT, world_id TEXT, world_name TEXT, image_url TEXT, invite_message TEXT, request_message TEXT, response_message TEXT, expired BIGINT);
CREATE TABLE IF NOT EXISTS account_abc.notifications_v2 (id TEXT PRIMARY KEY, created_at TEXT, updated_at TEXT, expires_at TEXT, type TEXT, link TEXT, link_text TEXT, message TEXT, title TEXT, image_url TEXT, seen BIGINT, sender_user_id TEXT, sender_username TEXT, data TEXT, responses TEXT, details TEXT);
CREATE TABLE IF NOT EXISTS account_abc.moderation (user_id TEXT PRIMARY KEY, updated_at TEXT, display_name TEXT, block BIGINT, mute BIGINT);
CREATE TABLE IF NOT EXISTS account_abc.avatar_history (avatar_id TEXT PRIMARY KEY, created_at TEXT, time BIGINT);
CREATE TABLE IF NOT EXISTS account_abc.notes (user_id TEXT PRIMARY KEY, display_name TEXT, note TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS account_abc.mutual_graph_friends (friend_id TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS account_abc.mutual_graph_links (friend_id TEXT NOT NULL, mutual_id TEXT NOT NULL, PRIMARY KEY(friend_id, mutual_id));
CREATE TABLE IF NOT EXISTS account_abc.mutual_graph_links_old (friend_id TEXT NOT NULL, mutual_id TEXT NOT NULL, date TEXT NOT NULL, PRIMARY KEY(friend_id, mutual_id));
CREATE TABLE IF NOT EXISTS account_abc.mutual_graph_friends_old (friend_id TEXT PRIMARY KEY, last_updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS account_abc.mutual_graph_meta (friend_id TEXT PRIMARY KEY, last_fetched_at TEXT, opted_out BIGINT DEFAULT 0);
CREATE TABLE IF NOT EXISTS account_abc.tracked_nonfriends (user_id TEXT PRIMARY KEY, display_name TEXT, added_at TEXT);
CREATE TABLE IF NOT EXISTS account_abc.manual_relations_MANUEL (user_id_a TEXT NOT NULL, user_id_b TEXT NOT NULL, relation_type TEXT NOT NULL DEFAULT 'friend', added_at TEXT, PRIMARY KEY(user_id_a, user_id_b));

-- User indexes(4, mirrored from initUserSchema L1350-1361)
CREATE INDEX IF NOT EXISTS feed_online_offline_user_created_idx ON account_abc.feed_online_offline (user_id, created_at);
CREATE INDEX IF NOT EXISTS activity_sessions_v2_user_start_idx ON account_abc.activity_sessions_v2 (user_id, start_at);
CREATE INDEX IF NOT EXISTS activity_sessions_v2_user_end_idx ON account_abc.activity_sessions_v2 (user_id, end_at);
CREATE INDEX IF NOT EXISTS friend_log_history_user_id_idx ON account_abc.friend_log_history (user_id);

-- ── 3. Global DML(22 rows) ──
-- Columns listed in DDL order; explicit PK values for idempotent re-runs.
-- ON CONFLICT target is the table's full primary key column list.

-- public.gamelog_location(2)
INSERT INTO public.gamelog_location (id, created_at, location, world_id, world_name, time, group_name) VALUES (1, '2024-05-01T10:00:00Z', 'wrld_xyz:1~private(seed_a)~region', 'wrld_xyz:1', 'Test World', 1700000000, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.gamelog_location (id, created_at, location, world_id, world_name, time, group_name) VALUES (2, '2024-05-01T11:00:00Z', 'wrld_xyz:1~private(seed_b)~region', 'wrld_xyz:1', 'Test World', 1700003600, 'Test Group') ON CONFLICT (id) DO NOTHING;

-- public.gamelog_join_leave(2)
INSERT INTO public.gamelog_join_leave (id, created_at, type, display_name, location, user_id, time) VALUES (1, '2024-05-01T10:00:00Z', 'OnPlayerJoined', 'Alice', 'wrld_xyz:1', 'usr_alice', 1700000000) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.gamelog_join_leave (id, created_at, type, display_name, location, user_id, time) VALUES (2, '2024-05-01T10:05:00Z', 'OnPlayerLeft', 'Bob', 'wrld_xyz:1', 'usr_bob', 1700000300) ON CONFLICT (id) DO NOTHING;

-- public.gamelog_portal_spawn(1)
INSERT INTO public.gamelog_portal_spawn (id, created_at, display_name, location, user_id, instance_id, world_name) VALUES (1, '2024-05-01T10:00:00Z', 'Alice', 'wrld_xyz:1', 'usr_alice', 'inst_seed_1', 'Test World') ON CONFLICT (id) DO NOTHING;

-- public.gamelog_video_play(1)
INSERT INTO public.gamelog_video_play (id, created_at, video_url, video_name, video_id, location, display_name, user_id) VALUES (1, '2024-05-01T10:00:00Z', 'https://example.com/videos/seed.mp4', 'Seed Video', 'vid_seed_1', 'wrld_xyz:1', 'Alice', 'usr_alice') ON CONFLICT (id) DO NOTHING;

-- public.gamelog_resource_load(1)
INSERT INTO public.gamelog_resource_load (id, created_at, resource_url, resource_type, location) VALUES (1, '2024-05-01T10:00:00Z', 'https://example.com/resources/seed.bundle', 'avatar', 'wrld_xyz:1') ON CONFLICT (id) DO NOTHING;

-- public.gamelog_event(1)
INSERT INTO public.gamelog_event (id, created_at, data) VALUES (1, '2024-05-01T10:00:00Z', '{"seed":true}') ON CONFLICT (id) DO NOTHING;

-- public.gamelog_external(1)
INSERT INTO public.gamelog_external (id, created_at, message, display_name, user_id, location) VALUES (1, '2024-05-01T10:00:00Z', 'seed external event', 'Alice', 'usr_alice', 'wrld_xyz:1') ON CONFLICT (id) DO NOTHING;

-- public.cache_avatar(2)
INSERT INTO public.cache_avatar (id, added_at, author_id, author_name, created_at, description, image_url, name, release_status, thumbnail_image_url, updated_at, version) VALUES ('avtr_1', '2024-05-01T10:00:00Z', 'usr_creator', 'Creator', '2024-05-01T10:00:00Z', 'Avatar One', 'https://example.com/avatars/avtr_1.png', 'Avatar One', 'public', 'https://example.com/avatars/avtr_1_thumb.png', '2024-05-01T10:00:00Z', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.cache_avatar (id, added_at, author_id, author_name, created_at, description, image_url, name, release_status, thumbnail_image_url, updated_at, version) VALUES ('avtr_2', '2024-05-01T10:00:00Z', 'usr_creator', 'Creator', '2024-05-01T10:00:00Z', 'Avatar Two', 'https://example.com/avatars/avtr_2.png', 'Avatar Two', 'public', 'https://example.com/avatars/avtr_2_thumb.png', '2024-05-01T10:00:00Z', 2) ON CONFLICT (id) DO NOTHING;

-- public.cache_world(1)
INSERT INTO public.cache_world (id, added_at, author_id, author_name, created_at, description, image_url, name, release_status, thumbnail_image_url, updated_at, version) VALUES ('wrld_xyz:1', '2024-05-01T10:00:00Z', 'usr_creator', 'Creator', '2024-05-01T10:00:00Z', 'Seed World', 'https://example.com/worlds/wrld_xyz.png', 'Seed World', 'public', 'https://example.com/worlds/wrld_xyz_thumb.png', '2024-05-01T10:00:00Z', 1) ON CONFLICT (id) DO NOTHING;

-- public.favorite_world(1)
INSERT INTO public.favorite_world (id, created_at, world_id, group_name) VALUES (1, '2024-05-01T10:00:00Z', 'wrld_xyz:1', 'group_seed') ON CONFLICT (id) DO NOTHING;

-- public.favorite_avatar(1)
INSERT INTO public.favorite_avatar (id, created_at, avatar_id, group_name) VALUES (1, '2024-05-01T10:00:00Z', 'avtr_1', 'group_seed') ON CONFLICT (id) DO NOTHING;

-- public.favorite_friend(1)
INSERT INTO public.favorite_friend (id, created_at, user_id, group_name) VALUES (1, '2024-05-01T10:00:00Z', 'usr_alice', 'group_seed') ON CONFLICT (id) DO NOTHING;

-- public.memos(1)
INSERT INTO public.memos (user_id, edited_at, memo) VALUES ('usr_alice', '2024-05-01T10:00:00Z', 'Seed memo for Alice') ON CONFLICT (user_id) DO NOTHING;

-- public.world_memos(1)
INSERT INTO public.world_memos (world_id, edited_at, memo) VALUES ('wrld_xyz:1', '2024-05-01T10:00:00Z', 'Seed memo for world') ON CONFLICT (world_id) DO NOTHING;

-- public.avatar_memos(1)
INSERT INTO public.avatar_memos (avatar_id, edited_at, memo) VALUES ('avtr_1', '2024-05-01T10:00:00Z', 'Seed memo for avatar') ON CONFLICT (avatar_id) DO NOTHING;

-- public.avatar_tags(2)
INSERT INTO public.avatar_tags (avatar_id, tag, color) VALUES ('avtr_1', 'favorite', '#ff0000') ON CONFLICT (avatar_id, tag) DO NOTHING;
INSERT INTO public.avatar_tags (avatar_id, tag, color) VALUES ('avtr_1', 'hidden', '#000000') ON CONFLICT (avatar_id, tag) DO NOTHING;

-- public.cookies(1)
INSERT INTO public.cookies (key, value) VALUES ('seed_cookie_key', '{"auth":"seed"}') ON CONFLICT (key) DO NOTHING;

-- public.configs(1)
INSERT INTO public.configs (key, value) VALUES ('seed_config_key', '{"seed":true}') ON CONFLICT (key) DO NOTHING;

-- ── 4. User DML(29 rows) ──
-- Columns listed in DDL order; explicit PK values for idempotent re-runs.
-- ON CONFLICT target is the table's full primary key column list.

-- account_abc.feed_gps(2)
INSERT INTO account_abc.feed_gps (id, created_at, user_id, display_name, location, world_name, previous_location, time, group_name) VALUES (1, '2024-05-01T10:00:00Z', 'usr_alice', 'Alice', 'wrld_xyz:1', 'Test World', 'offline', 1700000000, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO account_abc.feed_gps (id, created_at, user_id, display_name, location, world_name, previous_location, time, group_name) VALUES (2, '2024-05-01T11:00:00Z', 'usr_bob', 'Bob', 'wrld_xyz:1', 'Test World', 'wrld_xyz:1', 1700003600, 'Test Group') ON CONFLICT (id) DO NOTHING;

-- account_abc.feed_status(2)
INSERT INTO account_abc.feed_status (id, created_at, user_id, display_name, status, status_description, previous_status, previous_status_description) VALUES (1, '2024-05-01T10:00:00Z', 'usr_alice', 'Alice', 'online', 'Seed status', 'offline', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO account_abc.feed_status (id, created_at, user_id, display_name, status, status_description, previous_status, previous_status_description) VALUES (2, '2024-05-01T11:00:00Z', 'usr_bob', 'Bob', 'join me', 'Seed status two', 'online', NULL) ON CONFLICT (id) DO NOTHING;

-- account_abc.feed_bio(1)
INSERT INTO account_abc.feed_bio (id, created_at, user_id, display_name, bio, previous_bio) VALUES (1, '2024-05-01T10:00:00Z', 'usr_alice', 'Alice', 'Seed bio for Alice', NULL) ON CONFLICT (id) DO NOTHING;

-- account_abc.feed_avatar(1)
INSERT INTO account_abc.feed_avatar (id, created_at, user_id, display_name, owner_id, avatar_name, current_avatar_image_url, current_avatar_thumbnail_image_url, previous_current_avatar_image_url, previous_current_avatar_thumbnail_image_url) VALUES (1, '2024-05-01T10:00:00Z', 'usr_alice', 'Alice', 'usr_creator', 'Avatar One', 'https://example.com/avatars/avtr_1.png', 'https://example.com/avatars/avtr_1_thumb.png', NULL, NULL) ON CONFLICT (id) DO NOTHING;

-- account_abc.feed_online_offline(1)
INSERT INTO account_abc.feed_online_offline (id, created_at, user_id, display_name, type, location, world_name, time, group_name) VALUES (1, '2024-05-01T10:00:00Z', 'usr_alice', 'Alice', 'OnPlayerJoined', 'wrld_xyz:1', 'Test World', 1700000000, NULL) ON CONFLICT (id) DO NOTHING;

-- account_abc.activity_sync_state_v2(1)
INSERT INTO account_abc.activity_sync_state_v2 (user_id, updated_at, is_self, source_last_created_at, pending_session_start_at, cached_range_days) VALUES ('usr_alice', '2024-05-01T10:00:00Z', 1, '2024-05-01T10:00:00Z', 1700000000, 7) ON CONFLICT (user_id) DO NOTHING;

-- account_abc.activity_sessions_v2(1)
INSERT INTO account_abc.activity_sessions_v2 (session_id, user_id, start_at, end_at, is_open_tail, source_revision) VALUES (1, 'usr_alice', 1700000000, 1700003600, 0, 'rev_seed_1') ON CONFLICT (session_id) DO NOTHING;

-- account_abc.activity_bucket_cache_v2(1, composite PK explicit)
INSERT INTO account_abc.activity_bucket_cache_v2 (user_id, target_user_id, range_days, view_kind, exclude_key, bucket_version, raw_buckets_json, normalized_buckets_json, built_from_cursor, summary_json, built_at) VALUES ('usr_alice', '', 7, 'activity', '', 1, '[]', '[]', '', '{}', '2024-05-01T10:00:00Z') ON CONFLICT (user_id, target_user_id, range_days, view_kind, exclude_key) DO NOTHING;

-- account_abc.friend_log_current(1)
INSERT INTO account_abc.friend_log_current (user_id, display_name, trust_level, friend_number) VALUES ('usr_alice', 'Alice', 'Trusted User', 5) ON CONFLICT (user_id) DO NOTHING;

-- account_abc.friend_log_history(2)
INSERT INTO account_abc.friend_log_history (id, created_at, type, user_id, display_name, previous_display_name, trust_level, previous_trust_level, friend_number) VALUES (1, '2024-05-01T10:00:00Z', 'friend.add', 'usr_alice', 'Alice', NULL, 'Trusted User', NULL, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO account_abc.friend_log_history (id, created_at, type, user_id, display_name, previous_display_name, trust_level, previous_trust_level, friend_number) VALUES (2, '2024-05-02T10:00:00Z', 'friend.remove', 'usr_bob', 'Bob', NULL, 'Known User', 'Trusted User', 4) ON CONFLICT (id) DO NOTHING;

-- account_abc.notifications(1)
INSERT INTO account_abc.notifications (id, created_at, type, sender_user_id, sender_username, receiver_user_id, message, world_id, world_name, image_url, invite_message, request_message, response_message, expired) VALUES ('notif_seed_1', '2024-05-01T10:00:00Z', 'group.invite', 'usr_bob', 'Bob', 'usr_alice', 'Invite to seed group', NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT (id) DO NOTHING;

-- account_abc.notifications_v2(1)
INSERT INTO account_abc.notifications_v2 (id, created_at, updated_at, expires_at, type, link, link_text, message, title, image_url, seen, sender_user_id, sender_username, data, responses, details) VALUES ('notif_v2_seed_1', '2024-05-01T10:00:00Z', '2024-05-01T10:00:00Z', NULL, 'group.invite', NULL, NULL, 'Seed notification v2', NULL, NULL, 0, 'usr_bob', 'Bob', '{}', NULL, NULL) ON CONFLICT (id) DO NOTHING;

-- account_abc.moderation(1)
INSERT INTO account_abc.moderation (user_id, updated_at, display_name, block, mute) VALUES ('usr_bob', '2024-05-01T10:00:00Z', 'Bob', 1, 0) ON CONFLICT (user_id) DO NOTHING;

-- account_abc.avatar_history(1)
INSERT INTO account_abc.avatar_history (avatar_id, created_at, time) VALUES ('avtr_1', '2024-05-01T10:00:00Z', 1700000000) ON CONFLICT (avatar_id) DO NOTHING;

-- account_abc.notes(2)
INSERT INTO account_abc.notes (user_id, display_name, note, created_at) VALUES ('usr_alice', 'Alice', 'Seed note for Alice', '2024-05-01T10:00:00Z') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO account_abc.notes (user_id, display_name, note, created_at) VALUES ('usr_bob', 'Bob', 'Seed note for Bob', '2024-05-01T11:00:00Z') ON CONFLICT (user_id) DO NOTHING;

-- account_abc.mutual_graph_friends(2)
INSERT INTO account_abc.mutual_graph_friends (friend_id) VALUES ('usr_alice') ON CONFLICT (friend_id) DO NOTHING;
INSERT INTO account_abc.mutual_graph_friends (friend_id) VALUES ('usr_bob') ON CONFLICT (friend_id) DO NOTHING;

-- account_abc.mutual_graph_links(2, bidirectional)
INSERT INTO account_abc.mutual_graph_links (friend_id, mutual_id) VALUES ('usr_alice', 'usr_bob') ON CONFLICT (friend_id, mutual_id) DO NOTHING;
INSERT INTO account_abc.mutual_graph_links (friend_id, mutual_id) VALUES ('usr_bob', 'usr_alice') ON CONFLICT (friend_id, mutual_id) DO NOTHING;

-- account_abc.mutual_graph_links_old(1)
INSERT INTO account_abc.mutual_graph_links_old (friend_id, mutual_id, date) VALUES ('usr_alice', 'usr_bob', '2024-05-01') ON CONFLICT (friend_id, mutual_id) DO NOTHING;

-- account_abc.mutual_graph_friends_old(1)
INSERT INTO account_abc.mutual_graph_friends_old (friend_id, last_updated) VALUES ('usr_alice', '2024-05-01T10:00:00Z') ON CONFLICT (friend_id) DO NOTHING;

-- account_abc.mutual_graph_meta(2, one row with values, one row with NULLs)
INSERT INTO account_abc.mutual_graph_meta (friend_id, last_fetched_at, opted_out) VALUES ('usr_alice', '2024-05-01T10:00:00Z', 0) ON CONFLICT (friend_id) DO NOTHING;
INSERT INTO account_abc.mutual_graph_meta (friend_id, last_fetched_at, opted_out) VALUES ('usr_bob', NULL, NULL) ON CONFLICT (friend_id) DO NOTHING;

-- account_abc.tracked_nonfriends(1)
INSERT INTO account_abc.tracked_nonfriends (user_id, display_name, added_at) VALUES ('usr_carol', 'Carol', '2024-05-01T10:00:00Z') ON CONFLICT (user_id) DO NOTHING;

-- account_abc.manual_relations_MANUEL(1)
INSERT INTO account_abc.manual_relations_MANUEL (user_id_a, user_id_b, relation_type, added_at) VALUES ('usr_alice', 'usr_carol', 'friend', '2024-05-01T10:00:00Z') ON CONFLICT (user_id_a, user_id_b) DO NOTHING;

-- ── 5. Identity sequence sync(17 identity PK tables) ──
-- PG 的 GENERATED BY DEFAULT AS IDENTITY 序列不随显式 id 插入推进,这里把
-- 每张表的序列抬升到当前 MAX 值,保证导入后无显式 id 的 INSERT 不会拿到
-- 已占用的 id。表名单与上方 DDL 逐字一致;TEXT 主键/复合主键表无需处理。
-- (注意 activity_sessions_v2 的 identity 列名为 session_id,非 id。)

SELECT setval(pg_get_serial_sequence('public.gamelog_location','id'), COALESCE(MAX(id),1)) FROM public.gamelog_location;
SELECT setval(pg_get_serial_sequence('public.gamelog_join_leave','id'), COALESCE(MAX(id),1)) FROM public.gamelog_join_leave;
SELECT setval(pg_get_serial_sequence('public.gamelog_portal_spawn','id'), COALESCE(MAX(id),1)) FROM public.gamelog_portal_spawn;
SELECT setval(pg_get_serial_sequence('public.gamelog_video_play','id'), COALESCE(MAX(id),1)) FROM public.gamelog_video_play;
SELECT setval(pg_get_serial_sequence('public.gamelog_resource_load','id'), COALESCE(MAX(id),1)) FROM public.gamelog_resource_load;
SELECT setval(pg_get_serial_sequence('public.gamelog_event','id'), COALESCE(MAX(id),1)) FROM public.gamelog_event;
SELECT setval(pg_get_serial_sequence('public.gamelog_external','id'), COALESCE(MAX(id),1)) FROM public.gamelog_external;
SELECT setval(pg_get_serial_sequence('public.favorite_world','id'), COALESCE(MAX(id),1)) FROM public.favorite_world;
SELECT setval(pg_get_serial_sequence('public.favorite_avatar','id'), COALESCE(MAX(id),1)) FROM public.favorite_avatar;
SELECT setval(pg_get_serial_sequence('public.favorite_friend','id'), COALESCE(MAX(id),1)) FROM public.favorite_friend;
SELECT setval(pg_get_serial_sequence('account_abc.feed_gps','id'), COALESCE(MAX(id),1)) FROM account_abc.feed_gps;
SELECT setval(pg_get_serial_sequence('account_abc.feed_status','id'), COALESCE(MAX(id),1)) FROM account_abc.feed_status;
SELECT setval(pg_get_serial_sequence('account_abc.feed_bio','id'), COALESCE(MAX(id),1)) FROM account_abc.feed_bio;
SELECT setval(pg_get_serial_sequence('account_abc.feed_avatar','id'), COALESCE(MAX(id),1)) FROM account_abc.feed_avatar;
SELECT setval(pg_get_serial_sequence('account_abc.feed_online_offline','id'), COALESCE(MAX(id),1)) FROM account_abc.feed_online_offline;
SELECT setval(pg_get_serial_sequence('account_abc.activity_sessions_v2','session_id'), COALESCE(MAX(session_id),1)) FROM account_abc.activity_sessions_v2;
SELECT setval(pg_get_serial_sequence('account_abc.friend_log_history','id'), COALESCE(MAX(id),1)) FROM account_abc.friend_log_history;
